
  CREATE TABLE "CORRET"."TBOD_MAT_SUBCATEG" 
   (
	"CD_MAT_SUBCATEG" NUMBER(10,0) NOT NULL ENABLE, 
	"NOME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"DESCRICAO" VARCHAR2(250 BYTE) NULL ENABLE, 
	"ATIVO" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"APP" VARCHAR2(1 BYTE), 
	"WEB" VARCHAR2(1 BYTE), 
	 CONSTRAINT "PK_TBOD_MAT_SUBCATEG" PRIMARY KEY ("CD_MAT_SUBCATEG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS" ;


/*  
INSERT INTO "CORRET"."TBOD_MAT_SUBCATEG" (CD_MAT_SUBCATEG, NOME, DESCRICAO, ATIVO, APP, WEB) VALUES ('1', 'SUBCATEG 1', 'DESC SUBCATEG 1', 'S', 'S', 'S')
INSERT INTO "CORRET"."TBOD_MAT_SUBCATEG" (CD_MAT_SUBCATEG, NOME, DESCRICAO, ATIVO, APP, WEB) VALUES ('2', 'SUBCATEG 2', 'DESC SUBCATEG 2', 'S', 'S', 'N')
INSERT INTO "CORRET"."TBOD_MAT_SUBCATEG" (CD_MAT_SUBCATEG, NOME, DESCRICAO, ATIVO, APP, WEB) VALUES ('3', 'SUBCATEG 3', 'DESC SUBCATEG 3', 'S', 'N', 'S')
*/

ALTER TABLE TBOD_MAT_SUBCATEG
ADD CD_MAT_CATEG NUMBER(10,0) NULL
;
ALTER TABLE TBOD_MAT_SUBCATEG
ADD CONSTRAINT "FK_TBOD_MAT_SUBCATEG_CATEG" FOREIGN KEY ("CD_MAT_CATEG") 
REFERENCES "CORRET"."TBOD_MAT_CATEG" ("CD_MAT_CATEG")
;
UPDATE TBOD_MAT_SUBCATEG
SET CD_MAT_CATEG = 1
;
ALTER TABLE TBOD_MAT_SUBCATEG
MODIFY CD_MAT_CATEG NUMBER(10,0) NOT NULL
;
