
  CREATE TABLE "CORRET"."TBOD_MAT_SUBCATEG" 
   (
	"CD_MAT_SUBCATEG" NUMBER(10,0) NOT NULL ENABLE, 
	"NOME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"DESCRICAO" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"ATIVO" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PK_TBOD_MAT_SUBCATEG" PRIMARY KEY ("CD_MAT_SUBCATEG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CORRET_DADOS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "CORRET_DADOS" ;

/*  
INSERT INTO "CORRET"."TBOD_MAT_SUBCATEG" (CD_MAT_SUBCATEG, NOME, DESCRICAO, ATIVO) VALUES ('1', 'SUBCATEG 1', 'DESC SUBCATEG 1', 'S')
INSERT INTO "CORRET"."TBOD_MAT_SUBCATEG" (CD_MAT_SUBCATEG, NOME, DESCRICAO, ATIVO) VALUES ('2', 'SUBCATEG 2', 'DESC SUBCATEG 2', 'S')
INSERT INTO "CORRET"."TBOD_MAT_SUBCATEG" (CD_MAT_SUBCATEG, NOME, DESCRICAO, ATIVO) VALUES ('3', 'SUBCATEG 3', 'DESC SUBCATEG 3', 'S')
*/