/*COR-618 (BD - Nova tabela Detalhe Contratação) - 201808231558 - esert*/
/*DROP TABLE "CORRET"."TBOD_ARQUIVO_CONTRATACAO";*/
CREATE TABLE "CORRET"."TBOD_ARQUIVO_CONTRATACAO" (
"CD_EMPRESA" NUMBER(10,0) DEFAULT NULL NOT NULL ENABLE, 
"DATA_CRIACAO" DATE NOT NULL ENABLE, 
"NOME_ARQUIVO" NVARCHAR2(255) NOT NULL ENABLE,
"TAMANHO_ARQUIVO" NUMBER(10,0) NOT NULL ENABLE,
"TIPO_CONTEUDO" NVARCHAR2(20) NOT NULL ENABLE, 
"ARQUIVO" BLOB NOT NULL ENABLE, 
CONSTRAINT "PK_TBOD_ARQUIVO_CONTRATACAO" PRIMARY KEY ("CD_EMPRESA") ENABLE,
CONSTRAINT "FK_TBOD_ARQUIVO_CONT_EMPRESA" FOREIGN KEY ("CD_EMPRESA") REFERENCES TBOD_EMPRESA ("CD_EMPRESA") ENABLE
) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "CORRET_DADOS" 
 LOB ("ARQUIVO") STORE AS BASICFILE (
  TABLESPACE "CORRET_DADOS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;

