
  CREATE TABLE "CORRET"."TBOD_MAT_CATEG" 
   (	"CD_MAT_CATEG" NUMBER(10,0) NOT NULL ENABLE, 
	"NOME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"DESCRICAO" VARCHAR2(250 BYTE) NULL ENABLE, 
	"ATIVO" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PK_TBOD_MAT_CATEG" PRIMARY KEY ("CD_MAT_CATEG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS"  ENABLE, 
	 CONSTRAINT "SYS_C00294659" CHECK ("ATIVO" IS NOT NULL) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS" ;

  
 /*
INSERT INTO "CORRET"."TBOD_MAT_CATEG" (CD_MAT_CATEG, NOME, DESCRICAO, ATIVO) VALUES ('1', 'CATEG 1', 'DESC CATEG 1', 'S')
INSERT INTO "CORRET"."TBOD_MAT_CATEG" (CD_MAT_CATEG, NOME, DESCRICAO, ATIVO) VALUES ('2', 'CATEG 2', 'DESC CATEG 2', 'S')
INSERT INTO "CORRET"."TBOD_MAT_CATEG" (CD_MAT_CATEG, NOME, DESCRICAO, ATIVO) VALUES ('3', 'CATEG 3', 'DESC CATEG 3', 'S')
*/