CREATE TABLE CORRET.TBOD_REL_MAT_SUBCATEG 
(
 "CD_MAT_SUBCATEG" NUMBER(10,0) NOT NULL
,"CD_MAT_DIVULGA" NUMBER(10,0) NOT NULL
)
;

ALTER TABLE TBOD_REL_MAT_SUBCATEG 
ADD CONSTRAINT PK_TBOD_REL_MAT_SUBCATEG PRIMARY KEY ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA" )
;
ALTER TABLE TBOD_REL_MAT_SUBCATEG 
ADD CONSTRAINT "FK_TBOD_REL_MAT_SUB_SUBCATEG" FOREIGN KEY ("CD_MAT_SUBCATEG") 
REFERENCES "CORRET"."TBOD_MAT_SUBCATEG" ("CD_MAT_SUBCATEG")
;
ALTER TABLE TBOD_REL_MAT_SUBCATEG
ADD CONSTRAINT "FK_TBOD_REL_MAT_SUB_DIVULGA" FOREIGN KEY ("CD_MAT_DIVULGA") 
REFERENCES "CORRET"."TBOD_MAT_DIVULGA" ("CD_MAT_DIVULGA")
;

/*
ALTER TABLE TBOD_MAT_DIVULGA
DROP COLUMN CD_CATEGORIA
;

ALTER TABLE TBOD_MAT_DIVULGA
DROP COLUMN CD_SUB_CATEGORIA
;
*/

INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  1, 01); --1	1	1	papainoelvelo23_200x98.jpg
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  1, 02); --2	1	1	emktForcaAprovado200x296.jpg
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  1, 03); --3	1	1	emktForcaAprovado200x296.jpg
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  1, 04); --4	1	1	arduino_uno270x187.jpg
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  1, 05); --5	1	1	arduino_leonardo200x126.jpg
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  1, 06); --6	1	1	arduino_101_200x126.jpg
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  1, 28); --28	1	1	arduino_esplora200x196.png
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  2, 09); --9	1	2	Raspberry-Pi-Model-A-1-462x322.jpg
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  2, 10); --10	1	2	MAT 211
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  2, 11); --11	1	2	MAT 212
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  2, 12); --12	1	2	MAT 213
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  2, 13); --13	1	2	MAT 221
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  2, 14); --14	1	2	MAT 222
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  2, 15); --15	1	2	MAT 223
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  3, 43); --43	1	3	foto-perfil-fb-500x500-1.jpg
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  3, 44); --44	1	3	foto-perfil-fb-500x500-2.jpg
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  3, 45); --45	1	3	foto-perfil-fb-500x500-3.jpg
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  3, 46); --46	1	3	foto-perfil-fb-500x500-4.jpg
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  4, 29); --29	1	4	capa-fb-1280x555-1.jpg
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  4, 30); --30	1	4	capa-fb-1280x555-2.jpg
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  4, 31); --31	1	4	capa-fb-1280x555-3.jpg
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  4, 32); --32	1	4	capa-fb-1280x555-4.jpg
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  4, 33); --33	1	4	capa-fb-1280x555-5.jpg
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  4, 34); --34	1	4	capa-fb-1280x555-6.jpg
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  4, 35); --35	1	4	capa-fb-1280x555-7.jpg
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  4, 36); --36	1	4	capa-fb-1280x555-8.jpg
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  4, 37); --37	1	4	capa-fb-1280x555-9.jpg
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  4, 38); --38	1	4	capa-fb-1280x555-10.jpg
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  4, 39); --39	1	4	capa-fb-1280x555-11.jpg
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  4, 40); --40	1	4	capa-fb-1280x555-12.jpg
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  4, 41); --41	1	4	capa-fb-1280x555-13.jpg
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  4, 42); --42	1	4	capa-fb-1280x555-14.jpg
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  5, 47); --47	1	5	pf-dental-bem-estar-fb-wapp-1000x1000.jpg
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  5, 48); --48	1	5	pf-dental-estetica-fb-wapp-1000x1000.jpg
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  5, 49); --49	1	5	pf-dental-junior-fb-wapp-1000x1000.jpg
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  5, 50); --50	1	5	pf-dental-orto-fb-wapp-1000x1000.jpg
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  5, 51); --51	1	5	pf-dental-vip-fb-wapp-1000x1000.jpg
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  5, 52); --52	1	5	pf-dente-de-leite-fb-wapp-1000x1000.jpg
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  6, 53); --53	1	6	pme-integral-doc-le-fb-wapp-1000x1000.jpg
INSERT INTO TBOD_REL_MAT_SUBCATEG ( "CD_MAT_SUBCATEG", "CD_MAT_DIVULGA") VALUES (  6, 54); --54	1	6	pme-master-le-fb-wapp-1000x1000.jpg
