/*
COR-728 : BD - Nova tabela TBOD_TIPO_BLOQUEIO - 201809181056 - esert
*/
DROP TABLE "CORRET"."TBOD_TIPO_BLOQUEIO";

CREATE TABLE "CORRET"."TBOD_TIPO_BLOQUEIO" 
(
"CD_TIPO_BLOQUEIO" NUMBER(10,0) NOT NULL, 
"DESCRICAO" VARCHAR2(255) NOT NULL
);

ALTER TABLE "CORRET"."TBOD_TIPO_BLOQUEIO" 
ADD CONSTRAINT "PK_TBOD_TIPO_BLOQUEIO" PRIMARY KEY ("CD_TIPO_BLOQUEIO");

insert into TBOD_TIPO_BLOQUEIO 
(
 CD_TIPO_BLOQUEIO
,DESCRICAO
) values (
 0
,'SEM BLOQUEIO'
);

insert into TBOD_TIPO_BLOQUEIO 
(
 CD_TIPO_BLOQUEIO
,DESCRICAO
) values (
 1
,'PENDENTE ACEITAR CONTRATO DE CORRETAGEM OU INTERMEDIAÇÃO.'
);

COMMIT;
