--------------------------------------------------------
--  DDL for View VW_CORRETORA_SITUACAO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "CORRET"."VW_CORRETORA_SITUACAO" ("CD_PARCEIRO", "SITUACAO") AS 
  SELECT CD_PARCEIRO,
    CASE
      WHEN (SELECT COUNT(1)
        FROM TBOD_COR_ORG_PAGADORA
        WHERE TBOD_COR_ORG_PAGADORA.CD_PARCEIRO = TBOD_COR_CORRETORA.CD_PARCEIRO
        AND (DT_INATIVACAO_EBS                 IS NULL
        OR TRUNC(DT_INATIVACAO_EBS)             > TRUNC(SYSDATE))) = 0
      THEN 'Inativo'
      ELSE 'Ativo'
    END Situacao
  FROM TBOD_COR_CORRETORA
 ;
  GRANT SELECT ON "CORRET"."VW_CORRETORA_SITUACAO" TO "USUCORRET";
  GRANT SELECT ON "CORRET"."VW_CORRETORA_SITUACAO" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."VW_CORRETORA_SITUACAO" TO "CD_PORTALDOCORRETOR";
