--------------------------------------------------------
--  DDL for View VW_DADOS_BANCARIOS_CORRETORA
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "CORRET"."VW_DADOS_BANCARIOS_CORRETORA" ("NR_BANCO", "AGENCIA", "TIPO_CONTA", "NOME_BANCO", "CONTA", "NR_CNPJ") AS 
  SELECT BANCO NR_BANCO, AGENCIA AGENCIA, 'CC' TIPO_CONTA, BANK_NAME NOME_BANCO, CONTA_CORRENTE CONTA, CPF_CNPJ NR_CNPJ
from XODP_AP_VENDOR_PORTAL_V@lk_ebscorret EBS LEFT OUTER JOIN VW_BANCO BANCO ON EBS.BANCO = BANCO.BANK_NUMBER
 ;
  GRANT SELECT ON "CORRET"."VW_DADOS_BANCARIOS_CORRETORA" TO "USUCORRET";
  GRANT SELECT ON "CORRET"."VW_DADOS_BANCARIOS_CORRETORA" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."VW_DADOS_BANCARIOS_CORRETORA" TO "CD_PORTALDOCORRETOR";
