--------------------------------------------------------
--  DDL for View VW_EMPRESA
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "CORRET"."VW_EMPRESA" ("CD_CPF_CNPJ", "NM_EMPRESA", "CD_EMPRESA", "CD_CPF_CNPJ_CORRETORA") AS 
  SELECT CPF_CNPJ_EMPRESA CD_CPF_CNPJ,
    NOME_EMPRESA AS NM_EMPRESA,
    CODIGO_EMPRESA AS CD_EMPRESA,
    TO_NUMBER(REGEXP_REPLACE(CNPJ_CPF_CORRETOR,'[^0-9]*','')) AS CD_CPF_CNPJ_CORRETORA
  FROM XODP.xodp_com_empresas_portal_vw@LK_EBSCORRET
 ;
  GRANT SELECT ON "CORRET"."VW_EMPRESA" TO "USUCORRET";
  GRANT SELECT ON "CORRET"."VW_EMPRESA" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."VW_EMPRESA" TO "CD_PORTALDOCORRETOR";
