--------------------------------------------------------
--  DDL for Sequence SEQ_TBOD_COR_INF_IR_DET
--------------------------------------------------------

   CREATE SEQUENCE  "CORRET"."SEQ_TBOD_COR_INF_IR_DET"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 428001 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER ON "CORRET"."SEQ_TBOD_COR_INF_IR_DET" TO "USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_COR_INF_IR_DET" TO "USUCORRET";
  GRANT ALTER ON "CORRET"."SEQ_TBOD_COR_INF_IR_DET" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_COR_INF_IR_DET" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_COR_INF_IR_DET" TO "CD_PORTALDOCORRETOR";
