--------------------------------------------------------
--  DDL for Sequence SEQ_TBOD_ENDERECO
--------------------------------------------------------

   CREATE SEQUENCE  "CORRET"."SEQ_TBOD_ENDERECO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 7721 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER ON "CORRET"."SEQ_TBOD_ENDERECO" TO "USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_ENDERECO" TO "USUCORRET";
  GRANT ALTER ON "CORRET"."SEQ_TBOD_ENDERECO" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_ENDERECO" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_ENDERECO" TO "CD_PORTALDOCORRETOR";
