--------------------------------------------------------
--  DDL for Sequence SEQ_TBOD_COR_PERF_ACES_COR
--------------------------------------------------------

   CREATE SEQUENCE  "CORRET"."SEQ_TBOD_COR_PERF_ACES_COR"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 9802 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER ON "CORRET"."SEQ_TBOD_COR_PERF_ACES_COR" TO "USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_COR_PERF_ACES_COR" TO "USUCORRET";
  GRANT ALTER ON "CORRET"."SEQ_TBOD_COR_PERF_ACES_COR" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_COR_PERF_ACES_COR" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_COR_PERF_ACES_COR" TO "CD_PORTALDOCORRETOR";
