--------------------------------------------------------
--  DDL for Sequence SEQ_TBOD_BENEFICIO
--------------------------------------------------------

   CREATE SEQUENCE  "CORRET"."SEQ_TBOD_BENEFICIO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER ON "CORRET"."SEQ_TBOD_BENEFICIO" TO "USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_BENEFICIO" TO "USUCORRET";
  GRANT ALTER ON "CORRET"."SEQ_TBOD_BENEFICIO" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_BENEFICIO" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_BENEFICIO" TO "CD_PORTALDOCORRETOR";
