--------------------------------------------------------
--  DDL for Sequence SEQ_TBOD_FAIXA_FAT
--------------------------------------------------------

   CREATE SEQUENCE  "CORRET"."SEQ_TBOD_FAIXA_FAT"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER ON "CORRET"."SEQ_TBOD_FAIXA_FAT" TO "USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_FAIXA_FAT" TO "USUCORRET";
  GRANT ALTER ON "CORRET"."SEQ_TBOD_FAIXA_FAT" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_FAIXA_FAT" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_FAIXA_FAT" TO "CD_PORTALDOCORRETOR";
