--------------------------------------------------------
--  DDL for Sequence SEQ_TBOD_CON_EQ_PRO
--------------------------------------------------------

   CREATE SEQUENCE  "CORRET"."SEQ_TBOD_CON_EQ_PRO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10981 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER ON "CORRET"."SEQ_TBOD_CON_EQ_PRO" TO "USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_CON_EQ_PRO" TO "USUCORRET";
  GRANT ALTER ON "CORRET"."SEQ_TBOD_CON_EQ_PRO" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_CON_EQ_PRO" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_CON_EQ_PRO" TO "CD_PORTALDOCORRETOR";
