--------------------------------------------------------
--  DDL for Sequence SEQ_TBOD_PROSPECT_PARCEIRO
--------------------------------------------------------

   CREATE SEQUENCE  "CORRET"."SEQ_TBOD_PROSPECT_PARCEIRO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER ON "CORRET"."SEQ_TBOD_PROSPECT_PARCEIRO" TO "USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_PROSPECT_PARCEIRO" TO "USUCORRET";
  GRANT ALTER ON "CORRET"."SEQ_TBOD_PROSPECT_PARCEIRO" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_PROSPECT_PARCEIRO" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_PROSPECT_PARCEIRO" TO "CD_PORTALDOCORRETOR";
