--------------------------------------------------------
--  DDL for Sequence SEQ_TBOD_COR_TEMPL_PERFIL
--------------------------------------------------------

   CREATE SEQUENCE  "CORRET"."SEQ_TBOD_COR_TEMPL_PERFIL"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER ON "CORRET"."SEQ_TBOD_COR_TEMPL_PERFIL" TO "USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_COR_TEMPL_PERFIL" TO "USUCORRET";
  GRANT ALTER ON "CORRET"."SEQ_TBOD_COR_TEMPL_PERFIL" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_COR_TEMPL_PERFIL" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_COR_TEMPL_PERFIL" TO "CD_PORTALDOCORRETOR";
