--------------------------------------------------------
--  DDL for Sequence SEQ_TBOD_COR_FAIXA_FAT_ANUAL
--------------------------------------------------------

   CREATE SEQUENCE  "CORRET"."SEQ_TBOD_COR_FAIXA_FAT_ANUAL"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER ON "CORRET"."SEQ_TBOD_COR_FAIXA_FAT_ANUAL" TO "USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_COR_FAIXA_FAT_ANUAL" TO "USUCORRET";
  GRANT ALTER ON "CORRET"."SEQ_TBOD_COR_FAIXA_FAT_ANUAL" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_COR_FAIXA_FAT_ANUAL" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_COR_FAIXA_FAT_ANUAL" TO "CD_PORTALDOCORRETOR";
