--------------------------------------------------------
--  DDL for Sequence SEQ_TBOD_GRAU_RELACIONAMENTO
--------------------------------------------------------

   CREATE SEQUENCE  "CORRET"."SEQ_TBOD_GRAU_RELACIONAMENTO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER ON "CORRET"."SEQ_TBOD_GRAU_RELACIONAMENTO" TO "USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_GRAU_RELACIONAMENTO" TO "USUCORRET";
  GRANT ALTER ON "CORRET"."SEQ_TBOD_GRAU_RELACIONAMENTO" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_GRAU_RELACIONAMENTO" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_GRAU_RELACIONAMENTO" TO "CD_PORTALDOCORRETOR";
