--------------------------------------------------------
--  DDL for Sequence SEQ_TBOD_COR_SIT_PROSPECT_PARC
--------------------------------------------------------

   CREATE SEQUENCE  "CORRET"."SEQ_TBOD_COR_SIT_PROSPECT_PARC"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER ON "CORRET"."SEQ_TBOD_COR_SIT_PROSPECT_PARC" TO "USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_COR_SIT_PROSPECT_PARC" TO "USUCORRET";
  GRANT ALTER ON "CORRET"."SEQ_TBOD_COR_SIT_PROSPECT_PARC" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_COR_SIT_PROSPECT_PARC" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_COR_SIT_PROSPECT_PARC" TO "CD_PORTALDOCORRETOR";
