--------------------------------------------------------
--  DDL for Sequence SEQ_TBOD_COR_PROSPECT_PAR
--------------------------------------------------------

   CREATE SEQUENCE  "CORRET"."SEQ_TBOD_COR_PROSPECT_PAR"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 11242 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER ON "CORRET"."SEQ_TBOD_COR_PROSPECT_PAR" TO "USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_COR_PROSPECT_PAR" TO "USUCORRET";
  GRANT ALTER ON "CORRET"."SEQ_TBOD_COR_PROSPECT_PAR" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_COR_PROSPECT_PAR" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_COR_PROSPECT_PAR" TO "CD_PORTALDOCORRETOR";
