--------------------------------------------------------
--  DDL for Sequence SEQ_TBOD_COR_TELEFONE
--------------------------------------------------------

   CREATE SEQUENCE  "CORRET"."SEQ_TBOD_COR_TELEFONE"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 16463 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER ON "CORRET"."SEQ_TBOD_COR_TELEFONE" TO "USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_COR_TELEFONE" TO "USUCORRET";
  GRANT ALTER ON "CORRET"."SEQ_TBOD_COR_TELEFONE" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_COR_TELEFONE" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_COR_TELEFONE" TO "CD_PORTALDOCORRETOR";
