--------------------------------------------------------
--  DDL for Sequence SEQ_TBOD_COR_ANEXO
--------------------------------------------------------

   CREATE SEQUENCE  "CORRET"."SEQ_TBOD_COR_ANEXO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1601 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER ON "CORRET"."SEQ_TBOD_COR_ANEXO" TO "USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_COR_ANEXO" TO "USUCORRET";
  GRANT ALTER ON "CORRET"."SEQ_TBOD_COR_ANEXO" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_COR_ANEXO" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_COR_ANEXO" TO "CD_PORTALDOCORRETOR";
