--------------------------------------------------------
--  DDL for Sequence SEQ_TBOD_TEMPLATE_PERFIL
--------------------------------------------------------

   CREATE SEQUENCE  "CORRET"."SEQ_TBOD_TEMPLATE_PERFIL"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER ON "CORRET"."SEQ_TBOD_TEMPLATE_PERFIL" TO "USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_TEMPLATE_PERFIL" TO "USUCORRET";
  GRANT ALTER ON "CORRET"."SEQ_TBOD_TEMPLATE_PERFIL" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_TEMPLATE_PERFIL" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_TEMPLATE_PERFIL" TO "CD_PORTALDOCORRETOR";
