--------------------------------------------------------
--  DDL for Sequence SEQ_COR_USER
--------------------------------------------------------

   CREATE SEQUENCE  "CORRET"."SEQ_COR_USER"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 23204 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER ON "CORRET"."SEQ_COR_USER" TO "USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_COR_USER" TO "USUCORRET";
  GRANT ALTER ON "CORRET"."SEQ_COR_USER" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_COR_USER" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_COR_USER" TO "CD_PORTALDOCORRETOR";
