--------------------------------------------------------
--  DDL for Sequence SEQ_TBOD_COR_INF_IR_CAB
--------------------------------------------------------

   CREATE SEQUENCE  "CORRET"."SEQ_TBOD_COR_INF_IR_CAB"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 58181 CACHE 20 NOORDER  NOCYCLE ;
  GRANT ALTER ON "CORRET"."SEQ_TBOD_COR_INF_IR_CAB" TO "USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_COR_INF_IR_CAB" TO "USUCORRET";
  GRANT ALTER ON "CORRET"."SEQ_TBOD_COR_INF_IR_CAB" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_COR_INF_IR_CAB" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."SEQ_TBOD_COR_INF_IR_CAB" TO "CD_PORTALDOCORRETOR";
