--------------------------------------------------------
--  DDL for Procedure PRC_PRE_FECHAMENTO_IR
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CORRET"."PRC_PRE_FECHAMENTO_IR" (P_ANO_BASE IN NUMBER)
AS
  ativas        number(9) default 0;
  com_informes  number(9) default 0;
  sem_informes  number(9) default 0;
BEGIN
    
    DELETE FROM TBOD_COR_FEC_INFORME_DETALHE WHERE NR_NR_ANO_COMPETENCIA = P_ANO_BASE;
    DELETE FROM TBOD_COR_FEC_INFORME_RESUMO WHERE NR_NR_ANO = P_ANO_BASE;
    
    INSERT INTO TBOD_COR_FEC_INFORME_DETALHE(
    DT_VALID_FIS_JUR,
    NM_RESPONSAVEL,
    CD_RETENCAO,
    DS_RENDIMENTO,
    CD_EMPRESA_PAGADORA,
    NM_RAZAO_SOCIAL_PAGADORA,
    NR_CNPJ_PAGADORA,
    CD_ESTABELECIMENTO,
    CD_TRIBUTO,
    NR_ALIQUOTA,
    DT_FATOR_GERADOR,
    NR_NR_MES_COMPETENCIA,
    CD_TIPO_QUITACAO,
    VL_BRUTO,
    VL_IR,
    VL_DEDUCAO,
    CD_PARCEIRO,
    NR_NR_ANO_COMPETENCIA)
    SELECT MAX(VALID_FIS_JUR),MAX(RESPONSAVEL),MAX(CODIGO_RETENCAO),MAX(DESCRICAO_RENDIMENTO),
           MAX(COD_EMPRESA_PAGADORA),MAX(FONTE_PAGADORA_RAZAO_SOCIAL),FONTE_PAGADORA_CNPJ,MAX(COD_ESTAB),
           MAX(COD_TRIBUTO),
           MAX(ALIQUOTA),           
           MAX(DATA_FATOR_GERADOR),
           MES_COMPETENCIA,
           MAX(TP_QUITACAO),
           SUM(VLR_BRUTO),
           SUM(VLR_IR_RETIDO),
           SUM(DEDUCAO),
           TBOD_COR_CORRETORA.CD_PARCEIRO,
           ANO_COMPETENCIA
    FROM VW_CORRETORA_SITUACAO
    INNER JOIN TBOD_COR_CORRETORA 
    ON VW_CORRETORA_SITUACAO.CD_PARCEIRO = TBOD_COR_CORRETORA.CD_PARCEIRO
    INNER JOIN VW_INFORME_RENDIMENTOS
    ON    VW_INFORME_RENDIMENTOS.CPF_CGC = TBOD_COR_CORRETORA.NR_CNPJ
    WHERE  SITUACAO = 'Ativo'
    AND    ANO_COMPETENCIA  = P_ANO_BASE group by FONTE_PAGADORA_CNPJ, MES_COMPETENCIA, TBOD_COR_CORRETORA.CD_PARCEIRO, ANO_COMPETENCIA;
        
    --ATIVAS
    SELECT COUNT(1) INTO ativas FROM VW_CORRETORA_SITUACAO
    WHERE  SITUACAO = 'Ativo';
    
    --Com Informes
    SELECT COUNT(1) INTO com_informes FROM VW_CORRETORA_SITUACAO
    WHERE  SITUACAO = 'Ativo'
    AND    EXISTS(SELECT 1 FROM TBOD_COR_FEC_INFORME_DETALHE
                  WHERE  VW_CORRETORA_SITUACAO.CD_PARCEIRO = TBOD_COR_FEC_INFORME_DETALHE.CD_PARCEIRO
                  AND    TBOD_COR_FEC_INFORME_DETALHE.NR_NR_ANO_COMPETENCIA = P_ANO_BASE);

    --Sem Informes
    SELECT COUNT(1) INTO sem_informes FROM VW_CORRETORA_SITUACAO
    WHERE  SITUACAO = 'Ativo'
    AND    NOT EXISTS(SELECT 1 FROM TBOD_COR_FEC_INFORME_DETALHE
                      WHERE  VW_CORRETORA_SITUACAO.CD_PARCEIRO = TBOD_COR_FEC_INFORME_DETALHE.CD_PARCEIRO
                      AND    TBOD_COR_FEC_INFORME_DETALHE.NR_NR_ANO_COMPETENCIA = P_ANO_BASE);
    
    INSERT INTO TBOD_COR_FEC_INFORME_RESUMO(nr_nr_ano,nr_num_quantidade_ativa,nr_num_quantidade_com_informe,nr_num_quantidade_sem_informe)
    VALUES(P_ANO_BASE,ativas,com_informes,sem_informes);
    
END;
 

/

  GRANT EXECUTE ON "CORRET"."PRC_PRE_FECHAMENTO_IR" TO "USUCORRET";
  GRANT EXECUTE ON "CORRET"."PRC_PRE_FECHAMENTO_IR" TO "R_USUCORRET";
