--------------------------------------------------------
--  Ref Constraints for Table TBOD_COR_FUNCIONALIDADE_PERFIL
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_COR_FUNCIONALIDADE_PERFIL" ADD CONSTRAINT "R_24" FOREIGN KEY ("CD_PERFIL_ACESSO")
	  REFERENCES "CORRET"."TBOD_COR_PERF_ACESSO_CORRETORA" ("CD_PERFIL_ACESSO") ENABLE NOVALIDATE;
  ALTER TABLE "CORRET"."TBOD_COR_FUNCIONALIDADE_PERFIL" ADD CONSTRAINT "R_25" FOREIGN KEY ("CD_FUNCIONALIDADE_CORRETORA")
	  REFERENCES "CORRET"."TBOD_COR_FUNC_CORRETORA" ("CD_FUNCIONALIDADE_CORRETORA") ENABLE NOVALIDATE;
