--------------------------------------------------------
--  Ref Constraints for Table TBOD_COR_ENDERECO_CORRETORA
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_COR_ENDERECO_CORRETORA" ADD CONSTRAINT "R_14" FOREIGN KEY ("CD_ENDERECO")
	  REFERENCES "CORRET"."TBOD_COR_ENDERECO" ("CD_ENDERECO") ENABLE NOVALIDATE;
  ALTER TABLE "CORRET"."TBOD_COR_ENDERECO_CORRETORA" ADD CONSTRAINT "R_15" FOREIGN KEY ("CD_PARCEIRO")
	  REFERENCES "CORRET"."TBOD_COR_CORRETORA" ("CD_PARCEIRO") ENABLE NOVALIDATE;
