--------------------------------------------------------
--  Ref Constraints for Table TBOD_FORCA_VENDA
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_FORCA_VENDA" ADD CONSTRAINT "FK_TBOD_FORCA_VENDA_CORR" FOREIGN KEY ("CD_CORRETORA")
	  REFERENCES "CORRET"."TBOD_CORRETORA" ("CD_CORRETORA") ENABLE;
  ALTER TABLE "CORRET"."TBOD_FORCA_VENDA" ADD CONSTRAINT "FK_TBOD_FORCA_VENDA_LOGIN" FOREIGN KEY ("CD_LOGIN")
	  REFERENCES "CORRET"."TBOD_LOGIN" ("CD_LOGIN") ENABLE;
  ALTER TABLE "CORRET"."TBOD_FORCA_VENDA" ADD CONSTRAINT "FK_TBOD_FORCA_VENDA_STATUS" FOREIGN KEY ("CD_STATUS_FORCA_VENDAS")
	  REFERENCES "CORRET"."TBOD_STATUS_FORCA_VENDA" ("CD_STATUS_FORCA_VENDAS") ENABLE;
