--------------------------------------------------------
--  Ref Constraints for Table TBOD_COR_FUNCIONARIO_CORRETORA
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_COR_FUNCIONARIO_CORRETORA" ADD CONSTRAINT "R_22" FOREIGN KEY ("CD_PARCEIRO")
	  REFERENCES "CORRET"."TBOD_COR_CORRETORA" ("CD_PARCEIRO") ENABLE NOVALIDATE;
  ALTER TABLE "CORRET"."TBOD_COR_FUNCIONARIO_CORRETORA" ADD CONSTRAINT "R_23" FOREIGN KEY ("CD_PERFIL_ACESSO")
	  REFERENCES "CORRET"."TBOD_COR_PERF_ACESSO_CORRETORA" ("CD_PERFIL_ACESSO") ON DELETE SET NULL ENABLE NOVALIDATE;
  ALTER TABLE "CORRET"."TBOD_COR_FUNCIONARIO_CORRETORA" ADD CONSTRAINT "R_26" FOREIGN KEY ("CD_SITUACAO_FUNCIONARIO_CORRET")
	  REFERENCES "CORRET"."TBOD_COR_SITUACAO_FUNCIONARIO" ("CD_SITUACAO_FUNCIONARIO_CORRET") ON DELETE SET NULL ENABLE NOVALIDATE;
