--------------------------------------------------------
--  Ref Constraints for Table TBOD_COR_TELEFONE_PROSP_PARC
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_COR_TELEFONE_PROSP_PARC" ADD CONSTRAINT "R_36" FOREIGN KEY ("CD_PROSPECT_PARCEIRO")
	  REFERENCES "CORRET"."TBOD_COR_PROSPECT_PARCEIRO" ("CD_PROSPECT_PARCEIRO") ENABLE NOVALIDATE;
  ALTER TABLE "CORRET"."TBOD_COR_TELEFONE_PROSP_PARC" ADD CONSTRAINT "R_40" FOREIGN KEY ("CD_TELEFONE")
	  REFERENCES "CORRET"."TBOD_COR_TELEFONE" ("CD_TELEFONE") ENABLE NOVALIDATE;
