--------------------------------------------------------
--  Ref Constraints for Table TBOD_COR_CORRETORA
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_COR_CORRETORA" ADD CONSTRAINT "R_3" FOREIGN KEY ("CD_CLASSIFICACAO_COMERCIAL")
	  REFERENCES "CORRET"."TBOD_COR_CLASS_COMERCIAL" ("CD_CLASSIFICACAO_COMERCIAL") ON DELETE SET NULL ENABLE NOVALIDATE;
  ALTER TABLE "CORRET"."TBOD_COR_CORRETORA" ADD CONSTRAINT "R_4" FOREIGN KEY ("CD_GRAU_RELACIONAMENTO")
	  REFERENCES "CORRET"."TBOD_COR_GRAU_RELACIONAMENTO" ("CD_GRAU_RELACIONAMENTO") ON DELETE SET NULL ENABLE NOVALIDATE;
  ALTER TABLE "CORRET"."TBOD_COR_CORRETORA" ADD CONSTRAINT "R_50" FOREIGN KEY ("CD_TIPO_PESSOA")
	  REFERENCES "CORRET"."TBOD_COR_TIPO_PESSOA" ("CD_TIPO_PESSOA") ON DELETE SET NULL ENABLE NOVALIDATE;
