--------------------------------------------------------
--  Ref Constraints for Table TBOD_VENDA
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_VENDA" ADD CONSTRAINT "FK_TBOD_VENDA_EMPRESA" FOREIGN KEY ("CD_EMPRESA")
	  REFERENCES "CORRET"."TBOD_EMPRESA" ("CD_EMPRESA") ENABLE;
  ALTER TABLE "CORRET"."TBOD_VENDA" ADD CONSTRAINT "FK_TBOD_VENDA_FORCA" FOREIGN KEY ("CD_FORCA_VENDAS")
	  REFERENCES "CORRET"."TBOD_FORCA_VENDA" ("CD_FORCA_VENDA") ENABLE;
  ALTER TABLE "CORRET"."TBOD_VENDA" ADD CONSTRAINT "FK_TBOD_VENDA_PLANO" FOREIGN KEY ("CD_PLANO")
	  REFERENCES "CORRET"."TBOD_PLANO" ("CD_PLANO") ENABLE;
  ALTER TABLE "CORRET"."TBOD_VENDA" ADD CONSTRAINT "FK_TBOD_VENDA_RESP_CONTR" FOREIGN KEY ("CD_RESPONSAVEL_CONTRATUAL")
	  REFERENCES "CORRET"."TBOD_RESPONSAVEL_CONTRATUAL" ("CD_RESPONSAVEL_CONTRATUAL") ENABLE;
  ALTER TABLE "CORRET"."TBOD_VENDA" ADD CONSTRAINT "FK_TBOD_VENDA_STATUS" FOREIGN KEY ("CD_STATUS_VENDA")
	  REFERENCES "CORRET"."TBOD_STATUS_VENDA" ("CD_STATUS_VENDA") ENABLE;
