--------------------------------------------------------
--  Ref Constraints for Table TBOD_COR_FUNC_TEMPLATE_PERF
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_COR_FUNC_TEMPLATE_PERF" ADD CONSTRAINT "R_30" FOREIGN KEY ("CD_TEMPLATE_PERFIL_ACESSO")
	  REFERENCES "CORRET"."TBOD_COR_TEMPL_PERFIL_ACESSO" ("CD_TEMPLATE_PERFIL_ACESSO") ENABLE NOVALIDATE;
  ALTER TABLE "CORRET"."TBOD_COR_FUNC_TEMPLATE_PERF" ADD CONSTRAINT "R_31" FOREIGN KEY ("CD_FUNCIONALIDADE_CORRETORA")
	  REFERENCES "CORRET"."TBOD_COR_FUNC_CORRETORA" ("CD_FUNCIONALIDADE_CORRETORA") ENABLE NOVALIDATE;
