--------------------------------------------------------
--  Ref Constraints for Table TBOD_CORRETORA
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_CORRETORA" ADD CONSTRAINT "FK_TBOD_CORRETORA_ENDERECO" FOREIGN KEY ("CD_ENDERECO")
	  REFERENCES "CORRET"."TBOD_ENDERECO" ("CD_ENDERECO") ENABLE;
  ALTER TABLE "CORRET"."TBOD_CORRETORA" ADD CONSTRAINT "FK_TBOD_CORRETORA_LOGIN" FOREIGN KEY ("CD_LOGIN")
	  REFERENCES "CORRET"."TBOD_LOGIN" ("CD_LOGIN") ENABLE;
