--------------------------------------------------------
--  Ref Constraints for Table TBOD_COR_TELEFONE_CORRETORA
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_COR_TELEFONE_CORRETORA" ADD CONSTRAINT "R_11" FOREIGN KEY ("CD_PARCEIRO")
	  REFERENCES "CORRET"."TBOD_COR_CORRETORA" ("CD_PARCEIRO") ENABLE NOVALIDATE;
  ALTER TABLE "CORRET"."TBOD_COR_TELEFONE_CORRETORA" ADD CONSTRAINT "R_13" FOREIGN KEY ("CD_TELEFONE")
	  REFERENCES "CORRET"."TBOD_COR_TELEFONE" ("CD_TELEFONE") ENABLE NOVALIDATE;
