--------------------------------------------------------
--  Ref Constraints for Table TBOD_CORRETORA_BANCO
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_CORRETORA_BANCO" ADD CONSTRAINT "FK_TBOD_CORRETORA_BANCO_CONTA" FOREIGN KEY ("CD_BANCO_CONTA")
	  REFERENCES "CORRET"."TBOD_BANCO_CONTA" ("CD_BANCO_CONTA") ENABLE;
  ALTER TABLE "CORRET"."TBOD_CORRETORA_BANCO" ADD CONSTRAINT "FK_TBOD_CORR_BANCO_CORR" FOREIGN KEY ("CD_CORRETORA")
	  REFERENCES "CORRET"."TBOD_CORRETORA" ("CD_CORRETORA") ENABLE;
