--------------------------------------------------------
--  Ref Constraints for Table TBOD_COR_PROSPECT_PARC_RAMO
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_COR_PROSPECT_PARC_RAMO" ADD CONSTRAINT "R_34" FOREIGN KEY ("CD_PROSPECT_PARCEIRO")
	  REFERENCES "CORRET"."TBOD_COR_PROSPECT_PARCEIRO" ("CD_PROSPECT_PARCEIRO") ENABLE NOVALIDATE;
  ALTER TABLE "CORRET"."TBOD_COR_PROSPECT_PARC_RAMO" ADD CONSTRAINT "R_35" FOREIGN KEY ("CD_RAMO_ATIVIDADE")
	  REFERENCES "CORRET"."TBOD_COR_RAMO_ATIVIDADE" ("CD_RAMO_ATIVIDADE") ENABLE NOVALIDATE;
