--------------------------------------------------------
--  Ref Constraints for Table TBOD_COR_DOC_ANEXO_CORRETORA
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_COR_DOC_ANEXO_CORRETORA" ADD CONSTRAINT "R_10" FOREIGN KEY ("CD_ANEXO")
	  REFERENCES "CORRET"."TBOD_COR_ANEXO" ("CD_ANEXO") ENABLE NOVALIDATE;
  ALTER TABLE "CORRET"."TBOD_COR_DOC_ANEXO_CORRETORA" ADD CONSTRAINT "R_27" FOREIGN KEY ("CD_GRUPO_ANEXO")
	  REFERENCES "CORRET"."TBOD_COR_GRUPO_ANEXO" ("CD_GRUPO_ANEXO") ENABLE NOVALIDATE;
  ALTER TABLE "CORRET"."TBOD_COR_DOC_ANEXO_CORRETORA" ADD CONSTRAINT "R_9" FOREIGN KEY ("CD_PARCEIRO")
	  REFERENCES "CORRET"."TBOD_COR_CORRETORA" ("CD_PARCEIRO") ENABLE NOVALIDATE;
