--------------------------------------------------------
--  Ref Constraints for Table TBOD_COR_TEL_CONT_EQP_PROSP
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_COR_TEL_CONT_EQP_PROSP" ADD CONSTRAINT "R_44" FOREIGN KEY ("CD_TELEFONE")
	  REFERENCES "CORRET"."TBOD_COR_TELEFONE" ("CD_TELEFONE") ENABLE NOVALIDATE;
  ALTER TABLE "CORRET"."TBOD_COR_TEL_CONT_EQP_PROSP" ADD CONSTRAINT "R_45" FOREIGN KEY ("CD_EQUIPE_PROSPECT")
	  REFERENCES "CORRET"."TBOD_COR_CONTATO_EQP_PROSPECT" ("CD_EQUIPE_PROSPECT") ENABLE NOVALIDATE;
