--------------------------------------------------------
--  Ref Constraints for Table TBOD_COR_PROSPECT_PARC_BENEF
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_COR_PROSPECT_PARC_BENEF" ADD CONSTRAINT "R_42" FOREIGN KEY ("CD_BENEFICIO")
	  REFERENCES "CORRET"."TBOD_COR_BENEFICIO" ("CD_BENEFICIO") ENABLE NOVALIDATE;
  ALTER TABLE "CORRET"."TBOD_COR_PROSPECT_PARC_BENEF" ADD CONSTRAINT "R_43" FOREIGN KEY ("CD_PROSPECT_PARCEIRO")
	  REFERENCES "CORRET"."TBOD_COR_PROSPECT_PARCEIRO" ("CD_PROSPECT_PARCEIRO") ENABLE NOVALIDATE;
