--------------------------------------------------------
--  DDL for Index IX_COR_INFORME_IR_CABECALHO_1
--------------------------------------------------------

  CREATE INDEX "CORRET"."IX_COR_INFORME_IR_CABECALHO_1" ON "CORRET"."TBOD_COR_INFORME_IR_CABECALHO" ("NR_NR_ANO", "CD_PARCEIRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS" ;
