--------------------------------------------------------
--  DDL for Index PK_TBOD_TIPO_PLANO
--------------------------------------------------------

  CREATE UNIQUE INDEX "CORRET"."PK_TBOD_TIPO_PLANO" ON "CORRET"."TBOD_TIPO_PLANO" ("CD_TIPO_PLANO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS" ;
