--------------------------------------------------------
--  DDL for Index XPKDETALHE_ANALISE_FECHAMENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "CORRET"."XPKDETALHE_ANALISE_FECHAMENTO" ON "CORRET"."TBOD_COR_FEC_INFORME_DETALHE" ("NR_NR_MES_COMPETENCIA", "CD_PARCEIRO", "NR_NR_ANO_COMPETENCIA", "NR_CNPJ_PAGADORA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS" ;
