--------------------------------------------------------
--  DDL for Index XPKFUNCIONALIDADE_X_TEMPLATE_P
--------------------------------------------------------

  CREATE UNIQUE INDEX "CORRET"."XPKFUNCIONALIDADE_X_TEMPLATE_P" ON "CORRET"."TBOD_COR_FUNC_TEMPLATE_PERF" ("CD_TEMPLATE_PERFIL_ACESSO", "CD_FUNCIONALIDADE_CORRETORA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS" ;
