--------------------------------------------------------
--  DDL for Index XPKORG_PAGADORA_CORRETORA
--------------------------------------------------------

  CREATE UNIQUE INDEX "CORRET"."XPKORG_PAGADORA_CORRETORA" ON "CORRET"."TBOD_COR_ORG_PAGADORA" ("CD_PARCEIRO", "CD_ORG_PAGADORA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS" ;
