--------------------------------------------------------
--  DDL for Index XPKPERFIL_ACESSO_CORRETORA
--------------------------------------------------------

  CREATE UNIQUE INDEX "CORRET"."XPKPERFIL_ACESSO_CORRETORA" ON "CORRET"."TBOD_COR_PERF_ACESSO_CORRETORA" ("CD_PERFIL_ACESSO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS" ;
