--------------------------------------------------------
--  DDL for Index XPKSITUACAO_FUNCIONARIO_CORRET
--------------------------------------------------------

  CREATE UNIQUE INDEX "CORRET"."XPKSITUACAO_FUNCIONARIO_CORRET" ON "CORRET"."TBOD_COR_SITUACAO_FUNCIONARIO" ("CD_SITUACAO_FUNCIONARIO_CORRET") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS" ;
