--------------------------------------------------------
--  DDL for Index XPKTELEFONE_PROSPECT_PARCEIRO
--------------------------------------------------------

  CREATE UNIQUE INDEX "CORRET"."XPKTELEFONE_PROSPECT_PARCEIRO" ON "CORRET"."TBOD_COR_TELEFONE_PROSP_PARC" ("CD_PROSPECT_PARCEIRO", "CD_TELEFONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS" ;
