--------------------------------------------------------
--  Constraints for Table TBOD_PLANO_VIDA
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_PLANO_VIDA" ADD CONSTRAINT "PK_TBOD_PLANO_VIDA" PRIMARY KEY ("CD_PLANO_VIDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CORRET_DADOS"  ENABLE;
  ALTER TABLE "CORRET"."TBOD_PLANO_VIDA" MODIFY ("CD_PLANO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_PLANO_VIDA" MODIFY ("CD_VIDA" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_PLANO_VIDA" MODIFY ("CD_PLANO_VIDA" NOT NULL ENABLE);
