--------------------------------------------------------
--  Constraints for Table TBOD_COR_CLASS_COMERCIAL
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_COR_CLASS_COMERCIAL" MODIFY ("DS_CLASSIFICACAO_COMERCIAL" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_CLASS_COMERCIAL" MODIFY ("CD_CLASSIFICACAO_COMERCIAL" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_CLASS_COMERCIAL" ADD CONSTRAINT "XPKCLASSIFICACAO_COMERCIAL" PRIMARY KEY ("CD_CLASSIFICACAO_COMERCIAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS"  ENABLE NOVALIDATE;
