--------------------------------------------------------
--  Constraints for Table TBOD_COR_FEC_INFORME_RESUMO
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_COR_FEC_INFORME_RESUMO" MODIFY ("NR_NUM_QUANTIDADE_SEM_INFORME" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_FEC_INFORME_RESUMO" MODIFY ("NR_NUM_QUANTIDADE_COM_INFORME" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_FEC_INFORME_RESUMO" MODIFY ("NR_NUM_QUANTIDADE_ATIVA" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_FEC_INFORME_RESUMO" MODIFY ("NR_NR_ANO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_FEC_INFORME_RESUMO" ADD CONSTRAINT "XPKRESUMO_ANALISE_FECHAMENTO_I" PRIMARY KEY ("NR_NR_ANO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS"  ENABLE NOVALIDATE;
