--------------------------------------------------------
--  Constraints for Table TBOD_FORCA_VENDA
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_FORCA_VENDA" ADD CONSTRAINT "PK_TBOD_FORCA_VENDA" PRIMARY KEY ("CD_FORCA_VENDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS"  ENABLE;
  ALTER TABLE "CORRET"."TBOD_FORCA_VENDA" MODIFY ("ATIVO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_FORCA_VENDA" MODIFY ("CPF" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_FORCA_VENDA" MODIFY ("CD_STATUS_FORCA_VENDAS" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_FORCA_VENDA" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_FORCA_VENDA" MODIFY ("CELULAR" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_FORCA_VENDA" MODIFY ("NOME" NOT NULL ENABLE);
