--------------------------------------------------------
--  Constraints for Table TBOD_COR_SITUACAO_FUNCIONARIO
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_COR_SITUACAO_FUNCIONARIO" MODIFY ("DS_SITUACAO_FUNCIONARIO_CORRET" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_SITUACAO_FUNCIONARIO" MODIFY ("CD_SITUACAO_FUNCIONARIO_CORRET" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_SITUACAO_FUNCIONARIO" ADD CONSTRAINT "XPKSITUACAO_FUNCIONARIO_CORRET" PRIMARY KEY ("CD_SITUACAO_FUNCIONARIO_CORRET")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS"  ENABLE NOVALIDATE;
