--------------------------------------------------------
--  Constraints for Table TBOD_COR_PAR_GRP_GERENC
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_COR_PAR_GRP_GERENC" MODIFY ("CD_GRUPO_GERENCIAL" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_PAR_GRP_GERENC" MODIFY ("CD_PARCEIRO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_PAR_GRP_GERENC" ADD CONSTRAINT "XPKCORRETORA_GRUPO_GERENCIAL" PRIMARY KEY ("CD_GRUPO_GERENCIAL", "CD_PARCEIRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS"  ENABLE NOVALIDATE;
