--------------------------------------------------------
--  Constraints for Table TBOD_PLANO_COBERTURA
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_PLANO_COBERTURA" ADD CONSTRAINT "PK_TBOD_PLANO_COBERTURA" PRIMARY KEY ("CD_PLANO_COBERTURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CORRET_DADOS"  ENABLE;
  ALTER TABLE "CORRET"."TBOD_PLANO_COBERTURA" MODIFY ("CD_COBERTURA" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_PLANO_COBERTURA" MODIFY ("CD_PLANO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_PLANO_COBERTURA" MODIFY ("CD_PLANO_COBERTURA" NOT NULL ENABLE);
