--------------------------------------------------------
--  Constraints for Table TBOD_BANCO_CONTA
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_BANCO_CONTA" ADD CONSTRAINT "PK_TBOD_BANCO_CONTA" PRIMARY KEY ("CD_BANCO_CONTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CORRET_DADOS"  ENABLE;
  ALTER TABLE "CORRET"."TBOD_BANCO_CONTA" MODIFY ("CODIGO_BANCO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_BANCO_CONTA" MODIFY ("CONTA" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_BANCO_CONTA" MODIFY ("AGENCIA" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_BANCO_CONTA" MODIFY ("CD_BANCO_CONTA" NOT NULL ENABLE);
