--------------------------------------------------------
--  Constraints for Table TBOD_COR_GRUPO_GERENCIAL
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_COR_GRUPO_GERENCIAL" MODIFY ("DS_GRUPO_GERENCIAL" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_GRUPO_GERENCIAL" MODIFY ("CD_GRUPO_GERENCIAL" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_GRUPO_GERENCIAL" ADD CONSTRAINT "XPKGRUPO_GERENCIAL" PRIMARY KEY ("CD_GRUPO_GERENCIAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS"  ENABLE NOVALIDATE;
