--------------------------------------------------------
--  Constraints for Table TBOD_LOG_EMAIL_BVPME
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_LOG_EMAIL_BVPME" ADD CONSTRAINT "TBOD_LOG_EMAIL_BVPME_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS"  ENABLE;
  ALTER TABLE "CORRET"."TBOD_LOG_EMAIL_BVPME" MODIFY ("CD_EMPRESA" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_LOG_EMAIL_BVPME" MODIFY ("DT_ENVIO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_LOG_EMAIL_BVPME" MODIFY ("ID" NOT NULL ENABLE);
