--------------------------------------------------------
--  Constraints for Table TBOD_COR_BENEFICIO
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_COR_BENEFICIO" MODIFY ("DS_BENEFICIO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_BENEFICIO" MODIFY ("CD_BENEFICIO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_BENEFICIO" ADD CONSTRAINT "XPKBENEFICIO" PRIMARY KEY ("CD_BENEFICIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS"  ENABLE NOVALIDATE;
