--------------------------------------------------------
--  Constraints for Table TBOD_COR_CONTATO_CORRETORA
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_COR_CONTATO_CORRETORA" MODIFY ("ID_MASTER" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_CONTATO_CORRETORA" MODIFY ("DS_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_CONTATO_CORRETORA" MODIFY ("NM_CONTATO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_CONTATO_CORRETORA" MODIFY ("CD_CONTATO_CORRETORA" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_CONTATO_CORRETORA" ADD CONSTRAINT "XPKCONTATO_CORRETORA" PRIMARY KEY ("CD_CONTATO_CORRETORA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS"  ENABLE NOVALIDATE;
