--------------------------------------------------------
--  Constraints for Table TBOD_COR_PERF_ACESSO_CORRETORA
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_COR_PERF_ACESSO_CORRETORA" MODIFY ("DS_PERFIL_ACESSO_CORRETORA" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_PERF_ACESSO_CORRETORA" MODIFY ("CD_PERFIL_ACESSO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_PERF_ACESSO_CORRETORA" ADD CONSTRAINT "XPKPERFIL_ACESSO_CORRETORA" PRIMARY KEY ("CD_PERFIL_ACESSO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS"  ENABLE NOVALIDATE;
