--------------------------------------------------------
--  Constraints for Table TBOD_COR_ENDERECO
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_COR_ENDERECO" MODIFY ("NM_CIDADE" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_ENDERECO" MODIFY ("NR_LOGRADOURO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_ENDERECO" MODIFY ("DS_LOGRADOURO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_ENDERECO" MODIFY ("CD_ENDERECO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_ENDERECO" ADD CONSTRAINT "XPKENDERECO" PRIMARY KEY ("CD_ENDERECO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS"  ENABLE NOVALIDATE;
