--------------------------------------------------------
--  Constraints for Table TBOD_JSON_REQUEST
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_JSON_REQUEST" ADD PRIMARY KEY ("CD_JSON_REQUEST")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS"  ENABLE;
  ALTER TABLE "CORRET"."TBOD_JSON_REQUEST" MODIFY ("CD_JSON_REQUEST" NOT NULL ENABLE);
