--------------------------------------------------------
--  Constraints for Table TBOD_COR_FUNCIONARIO_CORRETORA
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_COR_FUNCIONARIO_CORRETORA" MODIFY ("DT_ULTIMA_ATUALIZACAO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_FUNCIONARIO_CORRETORA" MODIFY ("DS_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_FUNCIONARIO_CORRETORA" MODIFY ("CD_PARCEIRO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_FUNCIONARIO_CORRETORA" MODIFY ("NR_CPF" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_FUNCIONARIO_CORRETORA" MODIFY ("NM_FUNCIONARIO_CORRETORA" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_FUNCIONARIO_CORRETORA" ADD CONSTRAINT "XPKFUNCIONARIO_CORRETORA" PRIMARY KEY ("NR_CPF", "CD_PARCEIRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS"  ENABLE NOVALIDATE;
