--------------------------------------------------------
--  Constraints for Table TBOD_EMPRESA_CONTATO
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_EMPRESA_CONTATO" ADD CONSTRAINT "TBOD_EMPRESA_CONTATO_PK" PRIMARY KEY ("CD_CONTATO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS"  ENABLE;
  ALTER TABLE "CORRET"."TBOD_EMPRESA_CONTATO" MODIFY ("CD_CONTATO" NOT NULL ENABLE);
