--------------------------------------------------------
--  Constraints for Table TBOD_COR_CORRETORA
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_COR_CORRETORA" MODIFY ("ID_ATIVO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_CORRETORA" MODIFY ("CD_TIPO_PESSOA" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_CORRETORA" MODIFY ("ID_CONTRATO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_CORRETORA" MODIFY ("ID_OPTANTE_SIMPLES" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_CORRETORA" MODIFY ("NR_CNPJ" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_CORRETORA" MODIFY ("NM_EMPRESA_PARCEIRA" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_CORRETORA" MODIFY ("CD_PARCEIRO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_CORRETORA" ADD CONSTRAINT "XPKCORRETORA" PRIMARY KEY ("CD_PARCEIRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS"  ENABLE NOVALIDATE;
