--------------------------------------------------------
--  Constraints for Table TBOD_COR_INFORME_IR_DETALHE
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_COR_INFORME_IR_DETALHE" MODIFY ("CD_INFORME_IR_DETALHE" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_INFORME_IR_DETALHE" ADD CONSTRAINT "XPKINFORME_IR_DETALHE" PRIMARY KEY ("CD_INFORME_IR_DETALHE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS"  ENABLE NOVALIDATE;
