--------------------------------------------------------
--  Constraints for Table TBOD_CORRETORA
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_CORRETORA" ADD CONSTRAINT "PK_TBOD_CORRETORA" PRIMARY KEY ("CD_CORRETORA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS"  ENABLE;
  ALTER TABLE "CORRET"."TBOD_CORRETORA" MODIFY ("STATUS_CNPJ" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_CORRETORA" MODIFY ("DATA_ABERTURA" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_CORRETORA" MODIFY ("SIMPLES_NACIONAL" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_CORRETORA" MODIFY ("REGIONAL" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_CORRETORA" MODIFY ("ATIVO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_CORRETORA" MODIFY ("CD_ENDERECO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_CORRETORA" MODIFY ("CNPJ" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_CORRETORA" MODIFY ("CODIGO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_CORRETORA" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_CORRETORA" MODIFY ("CD_CORRETORA" NOT NULL ENABLE);
