--------------------------------------------------------
--  Constraints for Table TBOD_PLANO
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_PLANO" ADD CONSTRAINT "PK_TBOD_PLANO" PRIMARY KEY ("CD_PLANO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS"  ENABLE;
  ALTER TABLE "CORRET"."TBOD_PLANO" MODIFY ("CODIGO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_PLANO" MODIFY ("CD_PLANO" NOT NULL ENABLE);
