--------------------------------------------------------
--  Constraints for Table TBOD_COR_LOGIN_TOKEN
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_COR_LOGIN_TOKEN" MODIFY ("NM_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_LOGIN_TOKEN" MODIFY ("CD_PARCEIRO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_LOGIN_TOKEN" MODIFY ("DT_CRIACAO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_LOGIN_TOKEN" MODIFY ("DS_TOKEN" NOT NULL ENABLE);
