--------------------------------------------------------
--  Constraints for Table TBOD_RESPONSAVEL_CONTRATUAL
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_RESPONSAVEL_CONTRATUAL" ADD CONSTRAINT "TBOD_RESPONSAVEL_CONTRATUA_PK" PRIMARY KEY ("CD_RESPONSAVEL_CONTRATUAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS"  ENABLE;
  ALTER TABLE "CORRET"."TBOD_RESPONSAVEL_CONTRATUAL" MODIFY ("CD_RESPONSAVEL_CONTRATUAL" NOT NULL ENABLE);
