--------------------------------------------------------
--  Constraints for Table TBOD_TOKEN_ACEITE
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_TOKEN_ACEITE" MODIFY ("DT_ENVIO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_TOKEN_ACEITE" MODIFY ("DT_EXPIRACAO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_TOKEN_ACEITE" ADD CONSTRAINT "TBOD_TOKEN_ACEITE_PK" PRIMARY KEY ("CD_VENDA", "CD_TOKEN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS"  ENABLE;
  ALTER TABLE "CORRET"."TBOD_TOKEN_ACEITE" MODIFY ("CD_VENDA" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_TOKEN_ACEITE" MODIFY ("CD_TOKEN" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_TOKEN_ACEITE" MODIFY ("EMAIL_ENVIO" NOT NULL ENABLE);
