--------------------------------------------------------
--  Constraints for Table TBOD_COR_TEMPL_PERFIL_ACESSO
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_COR_TEMPL_PERFIL_ACESSO" MODIFY ("DS_TEMPLATE_PERFIL_ACESSO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_TEMPL_PERFIL_ACESSO" MODIFY ("CD_TEMPLATE_PERFIL_ACESSO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_TEMPL_PERFIL_ACESSO" ADD CONSTRAINT "XPKTEMPLATE_PERFIL_ACESSO" PRIMARY KEY ("CD_TEMPLATE_PERFIL_ACESSO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS"  ENABLE NOVALIDATE;
