--------------------------------------------------------
--  Constraints for Table TBOD_COR_CTRL_FEC_INFORME
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_COR_CTRL_FEC_INFORME" ADD CONSTRAINT "XPKNR_ANO" PRIMARY KEY ("NR_ANO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS"  ENABLE;
  ALTER TABLE "CORRET"."TBOD_COR_CTRL_FEC_INFORME" MODIFY ("CD_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_CTRL_FEC_INFORME" MODIFY ("NR_ANO" NOT NULL ENABLE);
