--------------------------------------------------------
--  Constraints for Table TBOD_VENDA_VIDA
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_VENDA_VIDA" ADD CONSTRAINT "PK_TBOD_VENDA_VIDA" PRIMARY KEY ("CD_VENDA_VIDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS"  ENABLE;
  ALTER TABLE "CORRET"."TBOD_VENDA_VIDA" MODIFY ("CD_VENDA" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_VENDA_VIDA" MODIFY ("CD_VENDA_VIDA" NOT NULL ENABLE);
