--------------------------------------------------------
--  Constraints for Table TBOD_PERFIL
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_PERFIL" ADD PRIMARY KEY ("CD_PERFIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS"  ENABLE;
  ALTER TABLE "CORRET"."TBOD_PERFIL" MODIFY ("DT_INCLUSAO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_PERFIL" MODIFY ("DS_DESCRICAO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_PERFIL" MODIFY ("NM_PERFIL" NOT NULL ENABLE);
