--------------------------------------------------------
--  Constraints for Table TBOD_COR_ANEXO
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_COR_ANEXO" ADD CONSTRAINT "XPKANEXO" PRIMARY KEY ("CD_ANEXO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS"  ENABLE NOVALIDATE;
  ALTER TABLE "CORRET"."TBOD_COR_ANEXO" MODIFY ("NM_DS_ARQUIVO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_ANEXO" MODIFY ("DS_ARQUIVO_ANEXO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_ANEXO" MODIFY ("DS_ANEXO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_ANEXO" MODIFY ("CD_ANEXO" NOT NULL ENABLE);
