--------------------------------------------------------
--  Constraints for Table TBOD_DOCUMENTO
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_DOCUMENTO" ADD CONSTRAINT "PK_TBOD_DOCUMENTO" PRIMARY KEY ("CD_DOCUMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CORRET_DADOS"  ENABLE;
  ALTER TABLE "CORRET"."TBOD_DOCUMENTO" MODIFY ("BASE64" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_DOCUMENTO" MODIFY ("NOME_ARQUIVO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_DOCUMENTO" MODIFY ("CD_TIPO_ARQUIVO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_DOCUMENTO" MODIFY ("CD_TIPO_DOCUMENTO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_DOCUMENTO" MODIFY ("CD_DOCUMENTO" NOT NULL ENABLE);
