--------------------------------------------------------
--  Constraints for Table TBOD_CORRETORA_BANCO
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_CORRETORA_BANCO" ADD CONSTRAINT "PK_TBOD_CORRETORA_BANCO" PRIMARY KEY ("CD_CORRETORA_BANCO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CORRET_DADOS"  ENABLE;
  ALTER TABLE "CORRET"."TBOD_CORRETORA_BANCO" MODIFY ("CPF_RESPONSAVEL_LEGAL1" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_CORRETORA_BANCO" MODIFY ("CNAE" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_CORRETORA_BANCO" MODIFY ("CD_BANCO_CONTA" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_CORRETORA_BANCO" MODIFY ("CD_CORRETORA" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_CORRETORA_BANCO" MODIFY ("CD_CORRETORA_BANCO" NOT NULL ENABLE);
