--------------------------------------------------------
--  Constraints for Table TBOD_DEVICE_TOKEN
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_DEVICE_TOKEN" ADD PRIMARY KEY ("CD_DEVICE_TOKEN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CORRET_DADOS"  ENABLE;
  ALTER TABLE "CORRET"."TBOD_DEVICE_TOKEN" MODIFY ("DT_ATUALIZACAO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_DEVICE_TOKEN" MODIFY ("DT_INCLUSAO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_DEVICE_TOKEN" MODIFY ("NM_OPERATION_SYSTEM" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_DEVICE_TOKEN" MODIFY ("NM_MODEL" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_DEVICE_TOKEN" MODIFY ("ID_TOKEN" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_DEVICE_TOKEN" MODIFY ("CD_LOGIN" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_DEVICE_TOKEN" MODIFY ("CD_DEVICE_TOKEN" NOT NULL ENABLE);
