--------------------------------------------------------
--  Constraints for Table TBOD_COR_REPRESENTANTE_LEGAL
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_COR_REPRESENTANTE_LEGAL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_REPRESENTANTE_LEGAL" MODIFY ("STATUS_CNPJ" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_REPRESENTANTE_LEGAL" MODIFY ("DATA_ABERTURA" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_REPRESENTANTE_LEGAL" MODIFY ("OPTANTE_SIMPLES" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_REPRESENTANTE_LEGAL" MODIFY ("CNAE" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_REPRESENTANTE_LEGAL" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_REPRESENTANTE_LEGAL" MODIFY ("CELULAR" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_REPRESENTANTE_LEGAL" MODIFY ("ID_REPRESENTANTE" NOT NULL ENABLE);
