--------------------------------------------------------
--  Constraints for Table TBOD_VIDA
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_VIDA" ADD CONSTRAINT "PK_TBOD_VIDA" PRIMARY KEY ("CD_VIDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS"  ENABLE;
  ALTER TABLE "CORRET"."TBOD_VIDA" MODIFY ("NOME_MAE" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_VIDA" MODIFY ("DATA_NASCIMENTO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_VIDA" MODIFY ("SEXO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_VIDA" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_VIDA" MODIFY ("CD_VIDA" NOT NULL ENABLE);
