--------------------------------------------------------
--  Constraints for Table TBOD_ORIGEM_ASSOCIADO
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_ORIGEM_ASSOCIADO" ADD CONSTRAINT "PK_TBOD_ORIGEM_ASSOCIADO" PRIMARY KEY ("CD_ORIGEM_ASSOCIADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CORRET_DADOS"  ENABLE;
  ALTER TABLE "CORRET"."TBOD_ORIGEM_ASSOCIADO" MODIFY ("DECRICAO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_ORIGEM_ASSOCIADO" MODIFY ("CD_ORIGEM_ASSOCIADO" NOT NULL ENABLE);
