--------------------------------------------------------
--  Constraints for Table TBOD_UPLOAD_FORCAVENDA
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_UPLOAD_FORCAVENDA" ADD CONSTRAINT "TBOD_UPLOAD_FORCAVENDA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS"  ENABLE;
  ALTER TABLE "CORRET"."TBOD_UPLOAD_FORCAVENDA" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_UPLOAD_FORCAVENDA" MODIFY ("DATA_CRIACAO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_UPLOAD_FORCAVENDA" MODIFY ("CSV_ARQUIVO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_UPLOAD_FORCAVENDA" MODIFY ("CD_CORRETORA" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_UPLOAD_FORCAVENDA" MODIFY ("ID" NOT NULL ENABLE);
