--------------------------------------------------------
--  Constraints for Table TBOD_COR_CONTATO_EQP_PROSPECT
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_COR_CONTATO_EQP_PROSPECT" MODIFY ("NM_EQUIPE_PROSPECT" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_CONTATO_EQP_PROSPECT" MODIFY ("CD_EQUIPE_PROSPECT" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_CONTATO_EQP_PROSPECT" ADD CONSTRAINT "XPKCONTATO_EQUIPE_PROSPECT" PRIMARY KEY ("CD_EQUIPE_PROSPECT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS"  ENABLE NOVALIDATE;
