--------------------------------------------------------
--  Constraints for Table TBOD_EMPRESA
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_EMPRESA" MODIFY ("CNAE" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_EMPRESA" ADD CONSTRAINT "PK_TBOD_EMPRESA" PRIMARY KEY ("CD_EMPRESA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS"  ENABLE;
  ALTER TABLE "CORRET"."TBOD_EMPRESA" MODIFY ("CD_ENDERECO" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_EMPRESA" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_EMPRESA" MODIFY ("CELULAR" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_EMPRESA" MODIFY ("TELEFONE" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_EMPRESA" MODIFY ("CONTATO_EMPRESA" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_EMPRESA" MODIFY ("REPRESENTANTE_LEGAL" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_EMPRESA" MODIFY ("RAMO_ATIVIDADE" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_EMPRESA" MODIFY ("CNPJ" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_EMPRESA" MODIFY ("RAZAO_SOCIAL" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_EMPRESA" MODIFY ("CD_EMPRESA" NOT NULL ENABLE);
