--------------------------------------------------------
--  Constraints for Table TBOD_COR_TEL_CONT_CORRETOR
--------------------------------------------------------

  ALTER TABLE "CORRET"."TBOD_COR_TEL_CONT_CORRETOR" MODIFY ("CD_TELEFONE" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_TEL_CONT_CORRETOR" MODIFY ("CD_CONTATO_CORRETORA" NOT NULL ENABLE);
  ALTER TABLE "CORRET"."TBOD_COR_TEL_CONT_CORRETOR" ADD CONSTRAINT "XPKTELEFONE_CONTATO_CORRETORA" PRIMARY KEY ("CD_CONTATO_CORRETORA", "CD_TELEFONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS"  ENABLE NOVALIDATE;
