--------------------------------------------------------
--  DDL for Table TBOD_DOCUMENTO
--------------------------------------------------------

  CREATE TABLE "CORRET"."TBOD_DOCUMENTO" 
   (	"CD_DOCUMENTO" NUMBER(10,0), 
	"CD_TIPO_DOCUMENTO" NUMBER(10,0), 
	"CD_TIPO_ARQUIVO" NUMBER(10,0), 
	"NOME_ARQUIVO" VARCHAR2(100 BYTE), 
	"BASE64" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "CORRET_DADOS" ;
