--------------------------------------------------------
--  DDL for Table TBOD_CORRETORA
--------------------------------------------------------

  CREATE TABLE "CORRET"."TBOD_CORRETORA" 
   (	"CD_CORRETORA" NUMBER(10,0), 
	"NOME" VARCHAR2(255 BYTE), 
	"CODIGO" VARCHAR2(30 BYTE), 
	"CNPJ" VARCHAR2(50 BYTE), 
	"CD_ENDERECO" NUMBER(10,0), 
	"ATIVO" CHAR(1 BYTE), 
	"REGIONAL" VARCHAR2(50 BYTE), 
	"CPF_RESPONSAVEL" VARCHAR2(13 BYTE), 
	"RAZAO_SOCIAL" VARCHAR2(255 BYTE), 
	"TELEFONE" VARCHAR2(15 BYTE), 
	"SIMPLES_NACIONAL" CHAR(1 BYTE), 
	"DATA_ABERTURA" DATE, 
	"STATUS_CNPJ" VARCHAR2(100 BYTE), 
	"NOME_REPRESENTANTE_LEGAL1" VARCHAR2(200 BYTE), 
	"NOME_REPRESENTANTE_LEGAL2" VARCHAR2(200 BYTE), 
	"CELULAR" VARCHAR2(11 BYTE), 
	"EMAIL" VARCHAR2(80 BYTE), 
	"CNAE" VARCHAR2(50 BYTE), 
	"CD_LOGIN" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS" ;
