--------------------------------------------------------
--  DDL for Table TBOD_COR_PROSPECT_PARC_RAMO
--------------------------------------------------------

  CREATE TABLE "CORRET"."TBOD_COR_PROSPECT_PARC_RAMO" 
   (	"CD_PROSPECT_PARCEIRO" NUMBER(10,0), 
	"CD_RAMO_ATIVIDADE" NUMBER(2,0), 
	"NUM_QUANTIDADE_VIDA" NUMBER(6,0), 
	"DS_OBSERVACAO" VARCHAR2(200 BYTE), 
	"TBOD_COR_PROSPECT_PARCEIRO" RAW(255), 
	"TBOD_COR_RAMO_ATIVIDADE" RAW(255)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS" ;
  GRANT DELETE ON "CORRET"."TBOD_COR_PROSPECT_PARC_RAMO" TO "USUCORRET";
  GRANT INSERT ON "CORRET"."TBOD_COR_PROSPECT_PARC_RAMO" TO "USUCORRET";
  GRANT SELECT ON "CORRET"."TBOD_COR_PROSPECT_PARC_RAMO" TO "USUCORRET";
  GRANT UPDATE ON "CORRET"."TBOD_COR_PROSPECT_PARC_RAMO" TO "USUCORRET";
  GRANT DELETE ON "CORRET"."TBOD_COR_PROSPECT_PARC_RAMO" TO "R_USUCORRET";
  GRANT INSERT ON "CORRET"."TBOD_COR_PROSPECT_PARC_RAMO" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."TBOD_COR_PROSPECT_PARC_RAMO" TO "R_USUCORRET";
  GRANT UPDATE ON "CORRET"."TBOD_COR_PROSPECT_PARC_RAMO" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."TBOD_COR_PROSPECT_PARC_RAMO" TO "CD_PORTALDOCORRETOR";
  GRANT INSERT ON "CORRET"."TBOD_COR_PROSPECT_PARC_RAMO" TO "CD_PORTALDOCORRETOR";
  GRANT DELETE ON "CORRET"."TBOD_COR_PROSPECT_PARC_RAMO" TO "CD_PORTALDOCORRETOR";
  GRANT UPDATE ON "CORRET"."TBOD_COR_PROSPECT_PARC_RAMO" TO "CD_PORTALDOCORRETOR";
