--------------------------------------------------------
--  DDL for Table TBOD_ORIGEM_ASSOCIADO
--------------------------------------------------------

  CREATE TABLE "CORRET"."TBOD_ORIGEM_ASSOCIADO" 
   (	"CD_ORIGEM_ASSOCIADO" NUMBER(10,0), 
	"DECRICAO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "CORRET_DADOS" ;
