--------------------------------------------------------
--  DDL for Table TBOD_EMPRESA_CONTATO
--------------------------------------------------------

  CREATE TABLE "CORRET"."TBOD_EMPRESA_CONTATO" 
   (	"CD_CONTATO" NUMBER(10,0), 
	"NOME" VARCHAR2(255 BYTE), 
	"EMAIL" VARCHAR2(80 BYTE), 
	"TELEFONE" VARCHAR2(15 BYTE), 
	"CELULAR" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS" ;
