--------------------------------------------------------
--  DDL for Table TBOD_VENDA
--------------------------------------------------------

  CREATE TABLE "CORRET"."TBOD_VENDA" 
   (	"CD_VENDA" NUMBER(10,0), 
	"CD_EMPRESA" NUMBER(10,0), 
	"CD_PLANO" NUMBER(10,0), 
	"CD_FORCA_VENDAS" NUMBER(10,0), 
	"DT_VENDA" DATE, 
	"CD_VENDA_VIDA" NUMBER(10,0), 
	"CD_STATUS_VENDA" NUMBER(10,0), 
	"FATURA_VENCIMENTO" NUMBER(2,0), 
	"TIPO_CONTA" VARCHAR2(10 BYTE), 
	"BANCO" VARCHAR2(10 BYTE), 
	"AGENCIA" VARCHAR2(10 BYTE), 
	"AGENCIA_DV" VARCHAR2(10 BYTE), 
	"CONTA" VARCHAR2(10 BYTE), 
	"CONTA_DV" VARCHAR2(10 BYTE), 
	"TIPO_PAGAMENTO" VARCHAR2(10 BYTE), 
	"PROPOSTA_DCMS" VARCHAR2(20 BYTE), 
	"CD_RESPONSAVEL_CONTRATUAL" NUMBER(10,0), 
	"DT_VIGENCIA" DATE, 
	"DT_MOVIMENTACAO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS" ;
