--------------------------------------------------------
--  DDL for Table TBOD_CORRETORA_BANCO
--------------------------------------------------------

  CREATE TABLE "CORRET"."TBOD_CORRETORA_BANCO" 
   (	"CD_CORRETORA_BANCO" NUMBER(10,0), 
	"CD_CORRETORA" NUMBER(10,0), 
	"CD_BANCO_CONTA" NUMBER(10,0), 
	"CNAE" VARCHAR2(50 BYTE), 
	"CPF_RESPONSAVEL_LEGAL1" VARCHAR2(15 BYTE), 
	"CPF_RESPONSAVEL_LEGAL2" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "CORRET_DADOS" ;
