--------------------------------------------------------
--  DDL for Table TBOD_COR_INFORME_IR_DETALHE
--------------------------------------------------------

  CREATE TABLE "CORRET"."TBOD_COR_INFORME_IR_DETALHE" 
   (	"NR_NR_MES" NUMBER(2,0), 
	"CD_RETENCAO" NUMBER(*,0), 
	"DS_RENDIMENTO" VARCHAR2(500 BYTE), 
	"VL_RENDIMENTO" NUMBER(15,2), 
	"VL_IMPOSTO_RETIDO" NUMBER(15,2), 
	"CD_INFORME_IR_CABECALHO" NUMBER(8,0), 
	"CD_INFORME_IR_DETALHE" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS" ;
  GRANT DELETE ON "CORRET"."TBOD_COR_INFORME_IR_DETALHE" TO "USUCORRET";
  GRANT INSERT ON "CORRET"."TBOD_COR_INFORME_IR_DETALHE" TO "USUCORRET";
  GRANT SELECT ON "CORRET"."TBOD_COR_INFORME_IR_DETALHE" TO "USUCORRET";
  GRANT UPDATE ON "CORRET"."TBOD_COR_INFORME_IR_DETALHE" TO "USUCORRET";
  GRANT DELETE ON "CORRET"."TBOD_COR_INFORME_IR_DETALHE" TO "R_USUCORRET";
  GRANT INSERT ON "CORRET"."TBOD_COR_INFORME_IR_DETALHE" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."TBOD_COR_INFORME_IR_DETALHE" TO "R_USUCORRET";
  GRANT UPDATE ON "CORRET"."TBOD_COR_INFORME_IR_DETALHE" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."TBOD_COR_INFORME_IR_DETALHE" TO "CD_PORTALDOCORRETOR";
  GRANT INSERT ON "CORRET"."TBOD_COR_INFORME_IR_DETALHE" TO "CD_PORTALDOCORRETOR";
  GRANT DELETE ON "CORRET"."TBOD_COR_INFORME_IR_DETALHE" TO "CD_PORTALDOCORRETOR";
  GRANT UPDATE ON "CORRET"."TBOD_COR_INFORME_IR_DETALHE" TO "CD_PORTALDOCORRETOR";
