--------------------------------------------------------
--  DDL for Table TBOD_COR_CONTATO_CORRETORA
--------------------------------------------------------

  CREATE TABLE "CORRET"."TBOD_COR_CONTATO_CORRETORA" 
   (	"CD_CONTATO_CORRETORA" NUMBER(10,0), 
	"NM_CONTATO" VARCHAR2(100 BYTE), 
	"DS_EMAIL" VARCHAR2(100 BYTE), 
	"ID_MASTER" CHAR(1 BYTE), 
	"CD_PARCEIRO" NUMBER(10,0), 
	"TBOD_COR_CORRETORA" RAW(255)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS" ;
  GRANT DELETE ON "CORRET"."TBOD_COR_CONTATO_CORRETORA" TO "USUCORRET";
  GRANT INSERT ON "CORRET"."TBOD_COR_CONTATO_CORRETORA" TO "USUCORRET";
  GRANT SELECT ON "CORRET"."TBOD_COR_CONTATO_CORRETORA" TO "USUCORRET";
  GRANT UPDATE ON "CORRET"."TBOD_COR_CONTATO_CORRETORA" TO "USUCORRET";
  GRANT DELETE ON "CORRET"."TBOD_COR_CONTATO_CORRETORA" TO "R_USUCORRET";
  GRANT INSERT ON "CORRET"."TBOD_COR_CONTATO_CORRETORA" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."TBOD_COR_CONTATO_CORRETORA" TO "R_USUCORRET";
  GRANT UPDATE ON "CORRET"."TBOD_COR_CONTATO_CORRETORA" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."TBOD_COR_CONTATO_CORRETORA" TO "CD_PORTALDOCORRETOR";
  GRANT INSERT ON "CORRET"."TBOD_COR_CONTATO_CORRETORA" TO "CD_PORTALDOCORRETOR";
  GRANT DELETE ON "CORRET"."TBOD_COR_CONTATO_CORRETORA" TO "CD_PORTALDOCORRETOR";
  GRANT UPDATE ON "CORRET"."TBOD_COR_CONTATO_CORRETORA" TO "CD_PORTALDOCORRETOR";
