--------------------------------------------------------
--  DDL for Table TBOD_EMPRESA
--------------------------------------------------------

  CREATE TABLE "CORRET"."TBOD_EMPRESA" 
   (	"CD_EMPRESA" NUMBER(10,0), 
	"RAZAO_SOCIAL" VARCHAR2(200 BYTE), 
	"CNPJ" VARCHAR2(50 BYTE), 
	"INC_ESTADUAL" VARCHAR2(15 BYTE), 
	"RAMO_ATIVIDADE" VARCHAR2(200 BYTE), 
	"NOME_FANTASIA" VARCHAR2(200 BYTE), 
	"REPRESENTANTE_LEGAL" VARCHAR2(50 BYTE), 
	"CONTATO_EMPRESA" CHAR(1 BYTE), 
	"TELEFONE" VARCHAR2(15 BYTE), 
	"CELULAR" VARCHAR2(15 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"CD_ENDERECO" NUMBER(10,0), 
	"EMP_DCMS" VARCHAR2(6 BYTE), 
	"CNAE" VARCHAR2(50 BYTE), 
	"CD_EMPRESA_CONTATO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS" ;
