--------------------------------------------------------
--  DDL for Table TBOD_COR_CORRETORA
--------------------------------------------------------

  CREATE TABLE "CORRET"."TBOD_COR_CORRETORA" 
   (	"CD_PARCEIRO" NUMBER(10,0), 
	"DT_VALIDADE_EBS" DATE, 
	"NM_EMPRESA_PARCEIRA" VARCHAR2(200 BYTE), 
	"NM_FANTASIA" VARCHAR2(200 BYTE), 
	"NR_CNPJ" NUMBER(14,0), 
	"NR_SUSEP" NUMBER(5,0), 
	"NR_PIS" NUMBER(11,0), 
	"ID_OPTANTE_SIMPLES" CHAR(1 BYTE), 
	"ID_CONTRATO" CHAR(1 BYTE), 
	"CD_CLASSIFICACAO_COMERCIAL" NUMBER(5,0), 
	"CD_GRAU_RELACIONAMENTO" NUMBER(3,0), 
	"CD_TIPO_PESSOA" CHAR(1 BYTE), 
	"ID_ATIVO" CHAR(1 BYTE), 
	"CD_REGIONAL_COMERCIAL" NUMBER(8,0), 
	"CD_CONSULTOR" NUMBER(8,0), 
	"DT_INCLUSAO" DATE, 
	"DT_ULTIMA_ATUALIZACAO" DATE, 
	"CD_USUARIO_ULTIMA_ATUALIZACAO" VARCHAR2(50 BYTE), 
	"CD_USUARIO_INCLUSAO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS" ;
  GRANT DELETE ON "CORRET"."TBOD_COR_CORRETORA" TO "USUCORRET";
  GRANT INSERT ON "CORRET"."TBOD_COR_CORRETORA" TO "USUCORRET";
  GRANT SELECT ON "CORRET"."TBOD_COR_CORRETORA" TO "USUCORRET";
  GRANT UPDATE ON "CORRET"."TBOD_COR_CORRETORA" TO "USUCORRET";
  GRANT DELETE ON "CORRET"."TBOD_COR_CORRETORA" TO "R_USUCORRET";
  GRANT INSERT ON "CORRET"."TBOD_COR_CORRETORA" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."TBOD_COR_CORRETORA" TO "R_USUCORRET";
  GRANT UPDATE ON "CORRET"."TBOD_COR_CORRETORA" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."TBOD_COR_CORRETORA" TO "ADMPWEB";
  GRANT SELECT ON "CORRET"."TBOD_COR_CORRETORA" TO "CD_CONVDIG";
  GRANT SELECT ON "CORRET"."TBOD_COR_CORRETORA" TO "CD_EXTRANET";
  GRANT SELECT ON "CORRET"."TBOD_COR_CORRETORA" TO "CD_IMPLANTACAO";
  GRANT SELECT ON "CORRET"."TBOD_COR_CORRETORA" TO "CD_TOTALDENT";
  GRANT SELECT ON "CORRET"."TBOD_COR_CORRETORA" TO "CD_REDEUNNA";
  GRANT SELECT ON "CORRET"."TBOD_COR_CORRETORA" TO "CD_BANCOIND";
  GRANT SELECT ON "CORRET"."TBOD_COR_CORRETORA" TO "CD_PORTAISBATCH";
  GRANT SELECT ON "CORRET"."TBOD_COR_CORRETORA" TO "CD_DENTALCORP";
  GRANT SELECT ON "CORRET"."TBOD_COR_CORRETORA" TO "CD_RESTRITO";
  GRANT SELECT ON "CORRET"."TBOD_COR_CORRETORA" TO "CD_BDPF";
  GRANT SELECT ON "CORRET"."TBOD_COR_CORRETORA" TO "CD_PREAPROVACAO";
  GRANT SELECT ON "CORRET"."TBOD_COR_CORRETORA" TO "CD_CONSULTOREXPRESS";
  GRANT SELECT ON "CORRET"."TBOD_COR_CORRETORA" TO "CD_ODONTOPREV";
  GRANT SELECT ON "CORRET"."TBOD_COR_CORRETORA" TO "CD_REDECRED";
  GRANT SELECT ON "CORRET"."TBOD_COR_CORRETORA" TO "CD_CARTEIRINHAVIRTUAL";
  GRANT SELECT ON "CORRET"."TBOD_COR_CORRETORA" TO "CD_PRIVIAN";
  GRANT SELECT ON "CORRET"."TBOD_COR_CORRETORA" TO "CD_PORTALDOCORRETOR";
  GRANT INSERT ON "CORRET"."TBOD_COR_CORRETORA" TO "CD_PORTALDOCORRETOR";
  GRANT DELETE ON "CORRET"."TBOD_COR_CORRETORA" TO "CD_PORTALDOCORRETOR";
  GRANT UPDATE ON "CORRET"."TBOD_COR_CORRETORA" TO "CD_PORTALDOCORRETOR";
