--------------------------------------------------------
--  DDL for Table TBOD_COR_ANEXO
--------------------------------------------------------

  CREATE TABLE "CORRET"."TBOD_COR_ANEXO" 
   (	"CD_ANEXO" NUMBER(10,0), 
	"DS_ANEXO" VARCHAR2(200 BYTE), 
	"DS_ARQUIVO_ANEXO" BLOB, 
	"NM_DS_ARQUIVO" VARCHAR2(200 BYTE), 
	"DT_PUBLICACAO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS" 
 LOB ("DS_ARQUIVO_ANEXO") STORE AS BASICFILE (
  TABLESPACE "CORRET_DADOS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  GRANT DELETE ON "CORRET"."TBOD_COR_ANEXO" TO "USUCORRET";
  GRANT INSERT ON "CORRET"."TBOD_COR_ANEXO" TO "USUCORRET";
  GRANT SELECT ON "CORRET"."TBOD_COR_ANEXO" TO "USUCORRET";
  GRANT UPDATE ON "CORRET"."TBOD_COR_ANEXO" TO "USUCORRET";
  GRANT DELETE ON "CORRET"."TBOD_COR_ANEXO" TO "R_USUCORRET";
  GRANT INSERT ON "CORRET"."TBOD_COR_ANEXO" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."TBOD_COR_ANEXO" TO "R_USUCORRET";
  GRANT UPDATE ON "CORRET"."TBOD_COR_ANEXO" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."TBOD_COR_ANEXO" TO "CD_PORTALDOCORRETOR";
  GRANT INSERT ON "CORRET"."TBOD_COR_ANEXO" TO "CD_PORTALDOCORRETOR";
  GRANT DELETE ON "CORRET"."TBOD_COR_ANEXO" TO "CD_PORTALDOCORRETOR";
  GRANT UPDATE ON "CORRET"."TBOD_COR_ANEXO" TO "CD_PORTALDOCORRETOR";
