--------------------------------------------------------
--  DDL for Table TBOD_TOKEN_ACEITE
--------------------------------------------------------

  CREATE TABLE "CORRET"."TBOD_TOKEN_ACEITE" 
   (	"CD_VENDA" NUMBER(10,0), 
	"CD_TOKEN" VARCHAR2(255 BYTE), 
	"IP" VARCHAR2(15 BYTE), 
	"DT_ACEITE" DATE, 
	"EMAIL_ENVIO" VARCHAR2(80 BYTE), 
	"DT_ENVIO" DATE, 
	"DT_EXPIRACAO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS" ;
