--------------------------------------------------------
--  DDL for Table TBOD_UPLOAD_FORCAVENDA
--------------------------------------------------------

  CREATE TABLE "CORRET"."TBOD_UPLOAD_FORCAVENDA" 
   (	"ID" NUMBER, 
	"CD_CORRETORA" NUMBER(10,0), 
	"CSV_ARQUIVO" VARCHAR2(50 BYTE), 
	"DATA_CRIACAO" DATE, 
	"STATUS" VARCHAR2(10 BYTE) DEFAULT 'PENDENTE', 
	"CRITICA" VARCHAR2(200 BYTE), 
	"NOME" VARCHAR2(100 BYTE), 
	"CPF" VARCHAR2(11 BYTE), 
	"DATA_NASCIMENTO" VARCHAR2(10 BYTE), 
	"CELULAR" VARCHAR2(14 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"DEPARTAMENTO" VARCHAR2(50 BYTE), 
	"CARGO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS" ;
