--------------------------------------------------------
--  DDL for Table TBOD_VIDA
--------------------------------------------------------

  CREATE TABLE "CORRET"."TBOD_VIDA" 
   (	"CD_VIDA" NUMBER(10,0), 
	"NOME" VARCHAR2(100 BYTE), 
	"CPF" VARCHAR2(13 BYTE), 
	"SEXO" CHAR(1 BYTE), 
	"DATA_NASCIMENTO" DATE, 
	"NOME_MAE" VARCHAR2(50 BYTE), 
	"CELULAR" VARCHAR2(15 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"CD_TITULAR" NUMBER(10,0), 
	"CD_ENDERECO" NUMBER(10,0), 
	"PF_PJ" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS" ;
