--------------------------------------------------------
--  DDL for Table TBOD_COR_INFORME_IR_CABECALHO
--------------------------------------------------------

  CREATE TABLE "CORRET"."TBOD_COR_INFORME_IR_CABECALHO" 
   (	"NM_FONTE_PAGADORA" VARCHAR2(200 BYTE), 
	"NR_CPF_CNPJ_FONTE_PAGADORA" NUMBER(16,0), 
	"DS_INFORMACOES_COMPLEMENTARES" VARCHAR2(500 BYTE), 
	"DT_RESPONSAVEL" DATE, 
	"NM_RESPONSAVEL" VARCHAR2(100 BYTE), 
	"CD_INFORME_IR_CABECALHO" NUMBER(8,0), 
	"CD_PARCEIRO" NUMBER(10,0), 
	"NR_NR_ANO" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS" ;
  GRANT DELETE ON "CORRET"."TBOD_COR_INFORME_IR_CABECALHO" TO "USUCORRET";
  GRANT INSERT ON "CORRET"."TBOD_COR_INFORME_IR_CABECALHO" TO "USUCORRET";
  GRANT SELECT ON "CORRET"."TBOD_COR_INFORME_IR_CABECALHO" TO "USUCORRET";
  GRANT UPDATE ON "CORRET"."TBOD_COR_INFORME_IR_CABECALHO" TO "USUCORRET";
  GRANT DELETE ON "CORRET"."TBOD_COR_INFORME_IR_CABECALHO" TO "R_USUCORRET";
  GRANT INSERT ON "CORRET"."TBOD_COR_INFORME_IR_CABECALHO" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."TBOD_COR_INFORME_IR_CABECALHO" TO "R_USUCORRET";
  GRANT UPDATE ON "CORRET"."TBOD_COR_INFORME_IR_CABECALHO" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."TBOD_COR_INFORME_IR_CABECALHO" TO "CD_PORTALDOCORRETOR";
  GRANT INSERT ON "CORRET"."TBOD_COR_INFORME_IR_CABECALHO" TO "CD_PORTALDOCORRETOR";
  GRANT DELETE ON "CORRET"."TBOD_COR_INFORME_IR_CABECALHO" TO "CD_PORTALDOCORRETOR";
  GRANT UPDATE ON "CORRET"."TBOD_COR_INFORME_IR_CABECALHO" TO "CD_PORTALDOCORRETOR";
