--------------------------------------------------------
--  DDL for Table TBOD_COR_PROSPECT_PARCEIRO
--------------------------------------------------------

  CREATE TABLE "CORRET"."TBOD_COR_PROSPECT_PARCEIRO" 
   (	"CD_PROSPECT_PARCEIRO" NUMBER(10,0), 
	"CD_FAIXA_FATURAMENTO_ANUAL" NUMBER(2,0), 
	"NUM_QUANTIDADE_POTENCIAL_VIDA" NUMBER(5,0), 
	"DS_OBSERVACAO_OPERADORA" VARCHAR2(500 BYTE), 
	"NM_RAZAO_SOCIAL" VARCHAR2(200 BYTE), 
	"DS_EMAIL" VARCHAR2(100 BYTE), 
	"DS_SITE" VARCHAR2(100 BYTE), 
	"NR_CNPJ" NUMBER(14,0), 
	"CD_SITUACAO_PROSPECT_PARCEIRO" NUMBER(8,0), 
	"DS_LOGRADOURO" VARCHAR2(200 BYTE), 
	"NR_LOGRADOURO" VARCHAR2(10 BYTE), 
	"NM_BAIRRO" VARCHAR2(90 BYTE), 
	"NM_CIDADE" VARCHAR2(90 BYTE), 
	"SG_UF" CHAR(2 BYTE), 
	"CD_CEP" NUMBER(8,0), 
	"CD_REGIONAL_COMERCIAL" NUMBER(8,0), 
	"DT_ULTIMO_ENVIO" DATE, 
	"DT_ULTIMA_ATUALIZACAO_SITUACAO" DATE, 
	"CD_USUARIO_ULTIMA_ATUALIZACAO" VARCHAR2(50 BYTE), 
	"DS_OBSERVACAO_STATUS" VARCHAR2(2048 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS" ;
  GRANT DELETE ON "CORRET"."TBOD_COR_PROSPECT_PARCEIRO" TO "USUCORRET";
  GRANT INSERT ON "CORRET"."TBOD_COR_PROSPECT_PARCEIRO" TO "USUCORRET";
  GRANT SELECT ON "CORRET"."TBOD_COR_PROSPECT_PARCEIRO" TO "USUCORRET";
  GRANT UPDATE ON "CORRET"."TBOD_COR_PROSPECT_PARCEIRO" TO "USUCORRET";
  GRANT DELETE ON "CORRET"."TBOD_COR_PROSPECT_PARCEIRO" TO "R_USUCORRET";
  GRANT INSERT ON "CORRET"."TBOD_COR_PROSPECT_PARCEIRO" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."TBOD_COR_PROSPECT_PARCEIRO" TO "R_USUCORRET";
  GRANT UPDATE ON "CORRET"."TBOD_COR_PROSPECT_PARCEIRO" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."TBOD_COR_PROSPECT_PARCEIRO" TO "CD_PORTALDOCORRETOR";
  GRANT INSERT ON "CORRET"."TBOD_COR_PROSPECT_PARCEIRO" TO "CD_PORTALDOCORRETOR";
  GRANT DELETE ON "CORRET"."TBOD_COR_PROSPECT_PARCEIRO" TO "CD_PORTALDOCORRETOR";
  GRANT UPDATE ON "CORRET"."TBOD_COR_PROSPECT_PARCEIRO" TO "CD_PORTALDOCORRETOR";
