--------------------------------------------------------
--  DDL for Table TBOD_JSON_REQUEST
--------------------------------------------------------

  CREATE TABLE "CORRET"."TBOD_JSON_REQUEST" 
   (	"CD_JSON_REQUEST" NUMBER(10,0), 
	"JSON" VARCHAR2(4000 BYTE), 
	"DT_CRIACAO" DATE, 
	"CD_FORCA_VENDA" VARCHAR2(20 BYTE), 
	"MODELO_CELULAR" VARCHAR2(500 BYTE), 
	"URL" VARCHAR2(200 BYTE) DEFAULT NULL, 
	"CD_CORRETORA" NUMBER(10,0), 
	"HEADER" VARCHAR2(3000 BYTE), 
	"PARAMETER" VARCHAR2(3000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS" ;
