--------------------------------------------------------
--  DDL for Table TBOD_PLANO_COBERTURA
--------------------------------------------------------

  CREATE TABLE "CORRET"."TBOD_PLANO_COBERTURA" 
   (	"CD_PLANO_COBERTURA" NUMBER(10,0), 
	"CD_PLANO" NUMBER(10,0), 
	"CD_COBERTURA" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "CORRET_DADOS" ;
