--------------------------------------------------------
--  DDL for Table TBOD_PERFIL_USUARIO
--------------------------------------------------------

  CREATE TABLE "CORRET"."TBOD_PERFIL_USUARIO" 
   (	"CD_USUARIO" VARCHAR2(20 BYTE), 
	"CD_PERFIL" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS" ;

   COMMENT ON COLUMN "CORRET"."TBOD_PERFIL_USUARIO"."CD_USUARIO" IS 'usuário(login) utilizado na autenticação, pode ser CPF, CNPJ, ODP...';
