--------------------------------------------------------
--  DDL for Table TBOD_DEVICE_TOKEN
--------------------------------------------------------

  CREATE TABLE "CORRET"."TBOD_DEVICE_TOKEN" 
   (	"CD_DEVICE_TOKEN" NUMBER(10,0), 
	"CD_LOGIN" NUMBER(10,0), 
	"ID_TOKEN" VARCHAR2(1000 BYTE), 
	"NM_MODEL" VARCHAR2(255 BYTE), 
	"NM_OPERATION_SYSTEM" VARCHAR2(200 BYTE), 
	"DT_INCLUSAO" DATE, 
	"DT_ATUALIZACAO" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "CORRET_DADOS" ;
