--------------------------------------------------------
--  DDL for Table TBOD_STATUS_FORCA_VENDA
--------------------------------------------------------

  CREATE TABLE "CORRET"."TBOD_STATUS_FORCA_VENDA" 
   (	"CD_STATUS_FORCA_VENDAS" NUMBER(10,0), 
	"DESCRICAO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS" ;
