--------------------------------------------------------
--  DDL for Table TBOD_PERFIL
--------------------------------------------------------

  CREATE TABLE "CORRET"."TBOD_PERFIL" 
   (	"CD_PERFIL" NUMBER(3,0), 
	"NM_PERFIL" VARCHAR2(255 BYTE), 
	"DS_DESCRICAO" VARCHAR2(500 BYTE), 
	"DT_INCLUSAO" DATE, 
	"DT_ALTERACAO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS" ;
