--------------------------------------------------------
--  DDL for Table TBOD_COR_FEC_INFORME_DETALHE
--------------------------------------------------------

  CREATE TABLE "CORRET"."TBOD_COR_FEC_INFORME_DETALHE" 
   (	"DT_VALID_FIS_JUR" DATE, 
	"NM_RESPONSAVEL" VARCHAR2(80 BYTE), 
	"CD_RETENCAO" NUMBER(10,0), 
	"DS_RENDIMENTO" VARCHAR2(100 BYTE), 
	"CD_EMPRESA_PAGADORA" VARCHAR2(3 BYTE), 
	"NM_RAZAO_SOCIAL_PAGADORA" VARCHAR2(100 BYTE), 
	"NR_CNPJ_PAGADORA" VARCHAR2(14 BYTE), 
	"CD_ESTABELECIMENTO" VARCHAR2(6 BYTE), 
	"CD_TRIBUTO" VARCHAR2(2 BYTE), 
	"NR_ALIQUOTA" NUMBER(15,2), 
	"DT_FATOR_GERADOR" DATE, 
	"NR_NR_MES_COMPETENCIA" NUMBER(2,0), 
	"CD_TIPO_QUITACAO" CHAR(1 BYTE), 
	"VL_BRUTO" NUMBER(17,2), 
	"VL_IR" NUMBER(17,2), 
	"VL_DEDUCAO" NUMBER(17,2), 
	"CD_PARCEIRO" NUMBER(10,0), 
	"NR_NR_ANO_COMPETENCIA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS" ;
  GRANT DELETE ON "CORRET"."TBOD_COR_FEC_INFORME_DETALHE" TO "USUCORRET";
  GRANT INSERT ON "CORRET"."TBOD_COR_FEC_INFORME_DETALHE" TO "USUCORRET";
  GRANT SELECT ON "CORRET"."TBOD_COR_FEC_INFORME_DETALHE" TO "USUCORRET";
  GRANT UPDATE ON "CORRET"."TBOD_COR_FEC_INFORME_DETALHE" TO "USUCORRET";
  GRANT DELETE ON "CORRET"."TBOD_COR_FEC_INFORME_DETALHE" TO "R_USUCORRET";
  GRANT INSERT ON "CORRET"."TBOD_COR_FEC_INFORME_DETALHE" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."TBOD_COR_FEC_INFORME_DETALHE" TO "R_USUCORRET";
  GRANT UPDATE ON "CORRET"."TBOD_COR_FEC_INFORME_DETALHE" TO "R_USUCORRET";
  GRANT SELECT ON "CORRET"."TBOD_COR_FEC_INFORME_DETALHE" TO "CD_PORTALDOCORRETOR";
  GRANT INSERT ON "CORRET"."TBOD_COR_FEC_INFORME_DETALHE" TO "CD_PORTALDOCORRETOR";
  GRANT DELETE ON "CORRET"."TBOD_COR_FEC_INFORME_DETALHE" TO "CD_PORTALDOCORRETOR";
  GRANT UPDATE ON "CORRET"."TBOD_COR_FEC_INFORME_DETALHE" TO "CD_PORTALDOCORRETOR";
