--------------------------------------------------------
--  DDL for Table TBOD_PLANO
--------------------------------------------------------

  CREATE TABLE "CORRET"."TBOD_PLANO" 
   (	"CD_PLANO" NUMBER(10,0), 
	"NOME_PLANO" VARCHAR2(50 BYTE), 
	"TITULO" VARCHAR2(50 BYTE), 
	"CD_TIPO_PLANO" NUMBER(10,0), 
	"VALOR_MENSAL" NUMBER(10,2), 
	"VALOR_ANUAL" NUMBER(10,2), 
	"ATIVO" VARCHAR2(1 BYTE), 
	"CODIGO" VARCHAR2(10 BYTE), 
	"SIGLA" VARCHAR2(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CORRET_DADOS" ;
