--------------------------------------------------------
--  DDL for Table TBOD_DOCUMENTO_ASSOCIADO
--------------------------------------------------------

  CREATE TABLE "CORRET"."TBOD_DOCUMENTO_ASSOCIADO" 
   (	"CD_DOCUMENTO_ASSOCIADO" NUMBER(10,0), 
	"CD_ORIGEM_ASSOCIADO" NUMBER(10,0), 
	"CD_ASSOCIADO" NUMBER(10,0), 
	"CD_DOCUMENTO" NUMBER(10,0), 
	"TBOD_CORRETORA" RAW(255)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "CORRET_DADOS" ;
