/*201810221424 - esert - COR-720:BD - Criar Tabela Generica P/ Arquivos*/
/*201810221424 - esert - vide COR-673:DB - Modelagem TBOD_PLANO_INFO e TBOD_ARQUIVO*/

/*DROP TABLE TBOD_ARQUIVO;*/

CREATE TABLE "CORRET"."TBOD_ARQUIVO"
(
"CD_ARQUIVO" NUMBER(10) NOT NULL, -- PK
"NOME_ARQUIVO" VARCHAR(255) NOT NULL,
"DATA_CRIACAO" DATE NOT NULL,
"TIPO_CONTEUDO" VARCHAR(255) NOT NULL,
"TAMANHO" NUMBER (10) NOT NULL,
"ARQUIVO" BLOB NOT NULL
);

ALTER TABLE TBOD_ARQUIVO
ADD CONSTRAINT "PK_TBOD_ARQUIVO" PRIMARY KEY ("CD_ARQUIVO");
