/*201810221811 - esert - COR-932:API - Novo GET /planoinfo */

/*
insert into TBOD_ARQUIVO
(
 CD_ARQUIVO	--NUMBER(10,0)	No		1	
,NOME_ARQUIVO	--VARCHAR2(255 BYTE)	No		2	
,DATA_CRIACAO	--DATE	No		3	
,TIPO_CONTEUDO	--VARCHAR2(255 BYTE)	No		4	
,TAMANHO	--NUMBER(10,0)	No		5	
,ARQUIVO	--BLOB	No		6	
) values (
 SEQ_TBOD_ARQUIVO.NEXTVAL --CD_ARQUIVO	--NUMBER(10,0)	No		1	
,'arduino-uno-schematic.pdf' --NOME_ARQUIVO	--VARCHAR2(255 BYTE)	No		2	
,SYSDATE --DATA_CRIACAO	--DATE	No		3	
,'application/pdf' --TIPO_CONTEUDO	--VARCHAR2(255 BYTE)	No		4	
,33516 --TAMANHO	--NUMBER(10,0)	No		5	
,hextoraw('a') --ARQUIVO	--BLOB	No		6	
);
*/
--1 linha inserido. --201810221818

/*
insert into TBOD_ARQUIVO
(
 CD_ARQUIVO	--NUMBER(10,0)	No		1	
,NOME_ARQUIVO	--VARCHAR2(255 BYTE)	No		2	
,DATA_CRIACAO	--DATE	No		3	
,TIPO_CONTEUDO	--VARCHAR2(255 BYTE)	No		4	
,TAMANHO	--NUMBER(10,0)	No		5	
,ARQUIVO	--BLOB	No		6	
) values (
 SEQ_TBOD_ARQUIVO.NEXTVAL --CD_ARQUIVO	--NUMBER(10,0)	No		1	
,'Arduino_Nano-Rev3.2-SCH.pdf' --NOME_ARQUIVO	--VARCHAR2(255 BYTE)	No		2	
,SYSDATE --DATA_CRIACAO	--DATE	No		3	
,'application/pdf' --TIPO_CONTEUDO	--VARCHAR2(255 BYTE)	No		4	
,81045 --TAMANHO	--NUMBER(10,0)	No		5	
,hextoraw('a') --ARQUIVO	--BLOB	No		6	
);
*/
--1 linha inserido. --201810221830

/*
insert into TBOD_ARQUIVO
(
 CD_ARQUIVO	--NUMBER(10,0)	No		1	
,NOME_ARQUIVO	--VARCHAR2(255 BYTE)	No		2	
,DATA_CRIACAO	--DATE	No		3	
,TIPO_CONTEUDO	--VARCHAR2(255 BYTE)	No		4	
,TAMANHO	--NUMBER(10,0)	No		5	
,ARQUIVO	--BLOB	No		6	
) values (
 SEQ_TBOD_ARQUIVO.NEXTVAL --CD_ARQUIVO	--NUMBER(10,0)	No		1	
,'2000px-Arduino_Logo.svg.png' --NOME_ARQUIVO	--VARCHAR2(255 BYTE)	No		2	
,SYSDATE --DATA_CRIACAO	--DATE	No		3	
,'application/png' --TIPO_CONTEUDO	--VARCHAR2(255 BYTE)	No		4	
,111815 --TAMANHO	--NUMBER(10,0)	No		5	
,hextoraw('a') --ARQUIVO	--BLOB	No		6	
);
*/
--1 linha inserido. --201810221843

/*
insert into TBOD_ARQUIVO
(
 CD_ARQUIVO	--NUMBER(10,0)	No		1	
,NOME_ARQUIVO	--VARCHAR2(255 BYTE)	No		2	
,DATA_CRIACAO	--DATE	No		3	
,TIPO_CONTEUDO	--VARCHAR2(255 BYTE)	No		4	
,TAMANHO	--NUMBER(10,0)	No		5	
,ARQUIVO	--BLOB	No		6	
) values (
 SEQ_TBOD_ARQUIVO.NEXTVAL --CD_ARQUIVO	--NUMBER(10,0)	No		1	
,'Raspberry-Pi-Model-Bplus-Product-Brief.pdf' --NOME_ARQUIVO	--VARCHAR2(255 BYTE)	No		2	
,SYSDATE --DATA_CRIACAO	--DATE	No		3	
,'application/pdf' --TIPO_CONTEUDO	--VARCHAR2(255 BYTE)	No		4	
,2796859 --TAMANHO	--NUMBER(10,0)	No		5	
,hextoraw('a') --ARQUIVO	--BLOB	No		6	
);
*/

/*
insert into TBOD_ARQUIVO
(
 CD_ARQUIVO	--NUMBER(10,0)	No		1	
,NOME_ARQUIVO	--VARCHAR2(255 BYTE)	No		2	
,DATA_CRIACAO	--DATE	No		3	
,TIPO_CONTEUDO	--VARCHAR2(255 BYTE)	No		4	
,TAMANHO	--NUMBER(10,0)	No		5	
,ARQUIVO	--BLOB	No		6	
) values (
 SEQ_TBOD_ARQUIVO.NEXTVAL --CD_ARQUIVO	--NUMBER(10,0)	No		1	
,'MagPi68.pdf' --NOME_ARQUIVO	--VARCHAR2(255 BYTE)	No		2	
,SYSDATE --DATA_CRIACAO	--DATE	No		3	
,'application/pdf' --TIPO_CONTEUDO	--VARCHAR2(255 BYTE)	No		4	
,23600773 --TAMANHO	--NUMBER(10,0)	No		5	
,hextoraw('a') --ARQUIVO	--BLOB	No		6	
);
*/

/*
insert into TBOD_ARQUIVO
(
 CD_ARQUIVO	--NUMBER(10,0)	No		1	
,NOME_ARQUIVO	--VARCHAR2(255 BYTE)	No		2	
,DATA_CRIACAO	--DATE	No		3	
,TIPO_CONTEUDO	--VARCHAR2(255 BYTE)	No		4	
,TAMANHO	--NUMBER(10,0)	No		5	
,ARQUIVO	--BLOB	No		6	
) values (
 SEQ_TBOD_ARQUIVO.NEXTVAL --CD_ARQUIVO	--NUMBER(10,0)	No		1	
,'raspilogo800x800.png' --NOME_ARQUIVO	--VARCHAR2(255 BYTE)	No		2	
,SYSDATE --DATA_CRIACAO	--DATE	No		3	
,'application/png' --TIPO_CONTEUDO	--VARCHAR2(255 BYTE)	No		4	
,8952 --TAMANHO	--NUMBER(10,0)	No		5	
,hextoraw('a') --ARQUIVO	--BLOB	No		6	
);
*/

--commit;
