/*201810221441 - esert - COR-928:DB - Criar TBOD_PLANO_INFO com campo Tipo_Segmento ("PF" | "PME")*/
/*201810221441 - esert - vide COR-673:DB - Modelagem TBOD_PLANO_INFO e TBOD_ARQUIVO*/

/*DROP TABLE "CORRET"."TBOD_PLANO_INFO";*/
CREATE TABLE "CORRET"."TBOD_PLANO_INFO"
(
"CD_PLANO_INFO" NUMBER(10) NOT NULL, -- PK será referenciada pela TBOD_PLANO.
"NOME_PLANO_INFO" VARCHAR(255) NOT NULL,
"DESCRICAO" VARCHAR(2000) NOT NULL, -- \n para quebra de linha
"CD_ARQUIVO_GERAL" NUMBER(10) NULL, -- FK TBOD_ARQUIVO.CD_ARQUIVO
"CD_ARQUIVO_CARENCIA" NUMBER(10) NULL, -- FK TBOD_ARQUIVO.CD_ARQUIVO
"CD_ARQUIVO_ICONE" NUMBER(10) NULL, -- FK TBOD_ARQUIVO.CD_ARQUIVO
"TIPO_SEGMENTO" VARCHAR(3) NOT NULL,
"ATIVO" VARCHAR(1) NOT NULL
);

ALTER TABLE "CORRET"."TBOD_PLANO_INFO"
ADD CONSTRAINT "PK_TBOD_PLANO_INFO" PRIMARY KEY ("CD_PLANO_INFO");

ALTER TABLE "CORRET"."TBOD_PLANO_INFO"
ADD CONSTRAINT "FK_ARQ_GERAL_TBOD_ARQUIVO" FOREIGN KEY ("CD_ARQUIVO_GERAL")
REFERENCES "CORRET"."TBOD_ARQUIVO" ("CD_ARQUIVO");

ALTER TABLE "CORRET"."TBOD_PLANO_INFO"
ADD CONSTRAINT "FK_ARQ_CARENCIA_TBOD_ARQUIVO" FOREIGN KEY ("CD_ARQUIVO_CARENCIA")
REFERENCES "CORRET"."TBOD_ARQUIVO" ("CD_ARQUIVO");

ALTER TABLE "CORRET"."TBOD_PLANO_INFO"
ADD CONSTRAINT "FK_ARQ_ICONE_TBOD_ARQUIVO" FOREIGN KEY ("CD_ARQUIVO_ICONE")
REFERENCES "CORRET"."TBOD_ARQUIVO" ("CD_ARQUIVO");
