/*201810221625 - esert - TBOD_PLANO_INFO.insert*/

/*
insert into TBOD_PLANO_INFO
(
 "CD_PLANO_INFO" --NUMBER(10) NOT NULL, -- PK será referenciada pela TBOD_PLANO.
,"NOME_PLANO_INFO" --VARCHAR(255) NOT NULL,
,"DESCRICAO" --VARCHAR(2000) NOT NULL, -- \n para quebra de linha
,"CD_ARQUIVO_GERAL" --NUMBER(10) NULL, -- FK TBOD_ARQUIVO.CD_ARQUIVO
,"CD_ARQUIVO_CARENCIA" --NUMBER(10) NULL, -- FK TBOD_ARQUIVO.CD_ARQUIVO
,"CD_ARQUIVO_ICONE" --NUMBER(10) NULL, -- FK TBOD_ARQUIVO.CD_ARQUIVO
,"TIPO_SEGMENTO" --VARCHAR(3) NOT NULL,
,"ATIVO" --VARCHAR(1) NOT NULL
)
values
(
 SEQ_TBOD_PLANO_INFO.NEXTVAL -- "CD_PLANO_INFO" --NUMBER(10) NOT NULL, -- PK será referenciada pela TBOD_PLANO.
,'Dente de Leite' --,"NOME_PLANO_INFO" --VARCHAR(255) NOT NULL,
,'Dente de Leite lin 1
Dente de Leite lin 2
Dente de Leite lin 3
Dente de Leite lin 4
Dente de Leite lin 5
.fim.
.' --,"DESCRICAO" --VARCHAR(2000) NOT NULL, -- \n para quebra de linha
,null --,"CD_ARQUIVO_GERAL" --NUMBER(10) NULL, -- FK TBOD_ARQUIVO.CD_ARQUIVO
,null --,"CD_ARQUIVO_CARENCIA" --NUMBER(10) NULL, -- FK TBOD_ARQUIVO.CD_ARQUIVO
,null --,"CD_ARQUIVO_ICONE" --NUMBER(10) NULL, -- FK TBOD_ARQUIVO.CD_ARQUIVO
,'PF' --,"TIPO_SEGMENTO" --VARCHAR(3) NOT NULL,
,'S' --,"ATIVO" --VARCHAR(1) NOT NULL
);
--1 linha inserido. --201810221619
*/

/*
insert into TBOD_PLANO_INFO
(
 "CD_PLANO_INFO" --NUMBER(10) NOT NULL, -- PK será referenciada pela TBOD_PLANO.
,"NOME_PLANO_INFO" --VARCHAR(255) NOT NULL,
,"DESCRICAO" --VARCHAR(2000) NOT NULL, -- \n para quebra de linha
,"CD_ARQUIVO_GERAL" --NUMBER(10) NULL, -- FK TBOD_ARQUIVO.CD_ARQUIVO
,"CD_ARQUIVO_CARENCIA" --NUMBER(10) NULL, -- FK TBOD_ARQUIVO.CD_ARQUIVO
,"CD_ARQUIVO_ICONE" --NUMBER(10) NULL, -- FK TBOD_ARQUIVO.CD_ARQUIVO
,"TIPO_SEGMENTO" --VARCHAR(3) NOT NULL,
,"ATIVO" --VARCHAR(1) NOT NULL
)
values
(
 SEQ_TBOD_PLANO_INFO.NEXTVAL -- "CD_PLANO_INFO" --NUMBER(10) NOT NULL, -- PK será referenciada pela TBOD_PLANO.
,'Dental Bem Estar' --,"NOME_PLANO_INFO" --VARCHAR(255) NOT NULL,
,'Dental Bem Estar lin 1
Dental Bem Estar lin 2
Dental Bem Estar lin 3
Dental Bem Estar lin 4
Dental Bem Estar lin 5
.fim.
.' --,"DESCRICAO" --VARCHAR(2000) NOT NULL, -- \n para quebra de linha
,null --,"CD_ARQUIVO_GERAL" --NUMBER(10) NULL, -- FK TBOD_ARQUIVO.CD_ARQUIVO
,null --,"CD_ARQUIVO_CARENCIA" --NUMBER(10) NULL, -- FK TBOD_ARQUIVO.CD_ARQUIVO
,null --,"CD_ARQUIVO_ICONE" --NUMBER(10) NULL, -- FK TBOD_ARQUIVO.CD_ARQUIVO
,'PF' --,"TIPO_SEGMENTO" --VARCHAR(3) NOT NULL,
,'S' --,"ATIVO" --VARCHAR(1) NOT NULL
);
--1 linha inserido. --201810221627
*/

/*
insert into TBOD_PLANO_INFO
(
 "CD_PLANO_INFO" --NUMBER(10) NOT NULL, -- PK será referenciada pela TBOD_PLANO.
,"NOME_PLANO_INFO" --VARCHAR(255) NOT NULL,
,"DESCRICAO" --VARCHAR(2000) NOT NULL, -- \n para quebra de linha
,"CD_ARQUIVO_GERAL" --NUMBER(10) NULL, -- FK TBOD_ARQUIVO.CD_ARQUIVO
,"CD_ARQUIVO_CARENCIA" --NUMBER(10) NULL, -- FK TBOD_ARQUIVO.CD_ARQUIVO
,"CD_ARQUIVO_ICONE" --NUMBER(10) NULL, -- FK TBOD_ARQUIVO.CD_ARQUIVO
,"TIPO_SEGMENTO" --VARCHAR(3) NOT NULL,
,"ATIVO" --VARCHAR(1) NOT NULL
)
values
(
 SEQ_TBOD_PLANO_INFO.NEXTVAL -- "CD_PLANO_INFO" --NUMBER(10) NOT NULL, -- PK será referenciada pela TBOD_PLANO.
,'Integral' --,"NOME_PLANO_INFO" --VARCHAR(255) NOT NULL,
,'Integral lin 1
Integral lin 2
Integral lin 3
Integral lin 4
Integral lin 5
.fim.
.' --,"DESCRICAO" --VARCHAR(2000) NOT NULL, -- \n para quebra de linha
,null --,"CD_ARQUIVO_GERAL" --NUMBER(10) NULL, -- FK TBOD_ARQUIVO.CD_ARQUIVO
,null --,"CD_ARQUIVO_CARENCIA" --NUMBER(10) NULL, -- FK TBOD_ARQUIVO.CD_ARQUIVO
,null --,"CD_ARQUIVO_ICONE" --NUMBER(10) NULL, -- FK TBOD_ARQUIVO.CD_ARQUIVO
,'PME' --,"TIPO_SEGMENTO" --VARCHAR(3) NOT NULL,
,'S' --,"ATIVO" --VARCHAR(1) NOT NULL
);
--1 linha inserido. --201810231444
*/

/*
insert into TBOD_PLANO_INFO
(
 "CD_PLANO_INFO" --NUMBER(10) NOT NULL, -- PK será referenciada pela TBOD_PLANO.
,"NOME_PLANO_INFO" --VARCHAR(255) NOT NULL,
,"DESCRICAO" --VARCHAR(2000) NOT NULL, -- \n para quebra de linha
,"CD_ARQUIVO_GERAL" --NUMBER(10) NULL, -- FK TBOD_ARQUIVO.CD_ARQUIVO
,"CD_ARQUIVO_CARENCIA" --NUMBER(10) NULL, -- FK TBOD_ARQUIVO.CD_ARQUIVO
,"CD_ARQUIVO_ICONE" --NUMBER(10) NULL, -- FK TBOD_ARQUIVO.CD_ARQUIVO
,"TIPO_SEGMENTO" --VARCHAR(3) NOT NULL,
,"ATIVO" --VARCHAR(1) NOT NULL
)
values
(
 SEQ_TBOD_PLANO_INFO.NEXTVAL -- "CD_PLANO_INFO" --NUMBER(10) NOT NULL, -- PK será referenciada pela TBOD_PLANO.
,'Master' --,"NOME_PLANO_INFO" --VARCHAR(255) NOT NULL,
,'Master lin 1
Master lin 2
Master lin 3
Master lin 4
Master lin 5
.fim.
.' --,"DESCRICAO" --VARCHAR(2000) NOT NULL, -- \n para quebra de linha
,null --,"CD_ARQUIVO_GERAL" --NUMBER(10) NULL, -- FK TBOD_ARQUIVO.CD_ARQUIVO
,null --,"CD_ARQUIVO_CARENCIA" --NUMBER(10) NULL, -- FK TBOD_ARQUIVO.CD_ARQUIVO
,null --,"CD_ARQUIVO_ICONE" --NUMBER(10) NULL, -- FK TBOD_ARQUIVO.CD_ARQUIVO
,'PME' --,"TIPO_SEGMENTO" --VARCHAR(3) NOT NULL,
,'S' --,"ATIVO" --VARCHAR(1) NOT NULL
);
--1 linha inserido. --201810231447
*/

commit;
