/*
COR-751 : DB - nova tabela TBOD_CONTRATO_MODELO - 201809101232 - esert
*/
--DROP TABLE "CORRET"."TBOD_CONTRATO_MODELO";

CREATE TABLE "CORRET"."TBOD_CONTRATO_MODELO" 
(
"CD_CONTRATO_MODELO" NUMBER(10,0) NOT NULL, 
"DT_CRIACAO" DATE NOT NULL, 
"ARQ_MODELO" BLOB NULL, 
CONSTRAINT "PK_TBOD_CONTRATO_MODELO" PRIMARY KEY ("CD_CONTRATO_MODELO")
);

