/*
COR-751 : DB - nova tabela TBOD_CONTRATO_MODELO - 201809101232 - esert
*/
DROP TABLE "CORRET"."TBOD_CONTRATO_MODELO";

CREATE TABLE "CORRET"."TBOD_CONTRATO_MODELO" 
(
"CD_CONTRATO_MODELO" NUMBER(10,0) NOT NULL, 
"DT_CRIACAO" DATE NOT NULL, 
"NOME_ARQUIVO" NVARCHAR2(255) NOT NULL, 
"TAMANHO_ARQUIVO" NUMBER(10,0) NOT NULL, 
"TIPO_CONTEUDO" NVARCHAR2(20) NOT NULL, 
"ARQUIVO" BLOB NULL, 
CONSTRAINT "PK_TBOD_CONTRATO_MODELO" PRIMARY KEY ("CD_CONTRATO_MODELO")
);

/*
alter TABLE "CORRET"."TBOD_CONTRATO_MODELO"
drop column "ARQ_MODELO" ;

alter TABLE "CORRET"."TBOD_CONTRATO_MODELO"
add "NOME_ARQUIVO" NVARCHAR2(255) NULL
add "TAMANHO_ARQUIVO" NUMBER(10,0) NULL
add "TIPO_CONTEUDO" NVARCHAR2(20)  NULL 
add "ARQUIVO" BLOB NULL
;

alter TABLE "CORRET"."TBOD_CONTRATO_MODELO"
modify "NOME_ARQUIVO" NOT NULL
modify "TAMANHO_ARQUIVO"  NOT NULL
modify "TIPO_CONTEUDO"  NOT NULL 
;
*/
