/*
COR-699 - Criar tabela TBOD_CONTRATO_CORRETORA
*/
CREATE TABLE CORRET.TBOD_CONTRATO_CORRETORA
(
  "CD_CORRETORA" NUMBER(10) NOT NULL
  CONSTRAINT PK_TBOD_CONTRATO_CORRETORA PRIMARY KEY,
  CONSTRAINT "FK_TBOD_CONTRATO_CORRETORA" FOREIGN KEY ("CD_CORRETORA")
  REFERENCES "CORRET"."TBOD_CORRETORA" ("CD_CORRETORA") ENABLE,
  "DT_ACEITE_CONTRATO" DATE NOT NULL,
  "TAM_ARQUIVO" NUMBER(10) NOT NULL,
  "TIPO_CONTEUDO" VARCHAR2(20) NOT NULL,
  "ARQUIVO" BLOB
);
COMMIT;